pom.xml

This will enable us to invoke Junit tests from github action.

Specify maven surefire plugin in pom.xml

---

services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/Artifact.java
services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/Image.java
services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/Ocl.java
services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/VM.java
services/ocl-loader/src/test/java/org/eclipse/osc/services/ocl/loader/OclLoaderTest.java
services/ocl-loader/src/test/resources/test.json
website/docs/ocl.md

What this PR does / why we need it:
- Fix the test suit.
Which issue this PR fixes:
Resolves #17

[#17] Update OCL base classes and test suit.

---

services/huaweicloud/pom.xml
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/HuaweiCloudOrchestratorPlugin.java
services/huaweicloud/src/main/resources/META-INF/services/org.apache.karaf.minho.boot.spi.Service
services/pom.xml

Add skeleton of Huawei Cloud plugin

---

services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/Ocl.java
services/ocl-loader/src/test/java/org/eclipse/osc/services/ocl/loader/OclLoaderTest.java

Suppress the exceptions in referTo().
fix #34

Suppress the exceptions in referTo().

---

services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/Ocl.java
services/ocl-loader/src/test/java/org/eclipse/osc/services/ocl/loader/OclLoaderTest.java

Add more tests for OCL-loader.

---

services/huaweicloud/pom.xml
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/AtomBuilder.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/BuilderContext.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/BuilderFactory.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/HuaweiCloudOrchestratorPlugin.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/HuaweiEnvBuilder.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/HuaweiImageBuilder.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/HuaweiResourceBuilder.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/enums/BuilderState.java
services/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/HuaweiCloudTest.java
services/huaweicloud/src/test/resources/huawei_test.json

What this PR does / why we need it:
Refine the skeleton of Huawei Cloud plugin.
Which issue this PR fixes:
Fix #32

Refine the skeleton for Huawei Cloud plugin

---

services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/Artifact.java
services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/Image.java
services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/RuntimeBase.java
services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/Security.java
services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/SecurityRule.java
services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/Storage.java
services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/Subnet.java
services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/VM.java
services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/VPC.java

Add RuntimeBase for meta.

---

services/huaweicloud/pom.xml
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/AtomBuilder.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/HuaweiCloudOrchestratorPlugin.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/HuaweiEnvBuilder.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/HuaweiImageBuilder.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/HuaweiResourceBuilder.java

Adding a SLF4j as the logging framework and move the huawei cloud plugins to use SLF4j

adding SLF4j as the logging framework

---

.gitignore
README.md
services/api/src/test/resources/test.json
services/huaweicloud/pom.xml
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/AtomBuilder.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/BuilderContext.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/BuilderFactory.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/HuaweiCloudOrchestratorPlugin.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/HuaweiEnvBuilder.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/HuaweiImageBuilder.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/HuaweiResourceBuilder.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/terraform/Ocl2Hcl.java
services/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/AtomBuilderTest.java
services/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/BuilderFactoryTest.java
services/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/HuaweiCloudOrchestratorPluginTest.java
services/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/HuaweiEnvBuilderTest.java
services/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/HuaweiImageBuilderTest.java
services/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/HuaweiResourceBuilderTest.java
services/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/terraform/Ocl2HclTest.java
services/huaweicloud/src/test/resources/huawei_test.json
services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/Provisioner.java
services/ocl-loader/src/test/java/org/eclipse/osc/services/ocl/loader/OclLoaderTest.java
services/ocl-loader/src/test/resources/test.json
website/docs/ocl.md

Add OCL2HCL translations.
fix #23

Add Ocl2Hcl.

---

services/huaweicloud/src/main/resources/packer/huaweicloud.json

Add image packer hcl template

---

services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/BuilderFactory.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/HuaweiEnvBuilder.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/HuaweiImageBuilder.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/HuaweiResourceBuilder.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/terraform/Ocl2Hcl.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/terraform/TFExecutor.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/utils/SystemCmd.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/exceptions/BuilderException.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/exceptions/TFExecutorException.java
services/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/AtomBuilderTest.java
services/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/BuilderFactoryTest.java
services/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/HuaweiEnvBuilderTest.java
services/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/HuaweiImageBuilderTest.java
services/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/HuaweiResourceBuilderTest.java
services/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/terraform/TFExecutorTest.java
services/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/utils/SystemCmdTest.java
services/huaweicloud/src/test/resources/huawei_test.json

Add terraform executor for huaweicloud plugin.

---

services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/HuaweiImageBuilder.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/packer/Ocl2Packer.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/packer/PackerExecutor.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/exceptions/PackerExecutorException.java
services/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/terraform/TFExecutorTest.java

Add packer impl for huaweicloud

---

services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/ObsOrchestratorStorage.java

Add OBS storage scheleton for huaweicloud

---

services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/HuaweiImageBuilder.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/HuaweiResourceBuilder.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/packer/Ocl2Packer.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/packer/PackerExecutor.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/packer/PackerVars.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/terraform/Ocl2Hcl.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/terraform/OclTFExecutor.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/terraform/TFExecutor.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/terraform/TFState.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/terraform/TFStateResource.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/terraform/TFStateResourceInstance.java
services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/utils/SystemCmd.java
services/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/HuaweiCloudOrchestratorPluginTest.java
services/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/HuaweiImageBuilderTest.java
services/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/packer/Ocl2PackerTest.java
services/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/packer/PackerExecutorTest.java
services/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/terraform/Ocl2HclTest.java
services/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/terraform/TFExecutorTest.java
services/huaweicloud/src/test/resources/huawei_test.json
services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/VM.java

Uniton test for packer&terraform

---

services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/ObsOrchestratorStorage.java
services/k8s/src/main/java/org/eclipse/osc/services/k8s/MinioOrchestratorStorage.java
services/openstack/src/main/java/org/eclipse/osc/orchestrator/plugin/openstack/SwiftOrchestratorStorage.java
services/orchestrator/src/main/java/org/eclipse/osc/orchestrator/FileOrchestratorStorage.java
services/orchestrator/src/main/java/org/eclipse/osc/orchestrator/OrchestratorStorage.java
services/orchestrator/src/test/java/org/eclipse/osc/orchestrator/OrchestratorServiceTest.java

Add plugin level storage api.

---

services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/HuaweiCloudOrchestratorPlugin.java
services/huaweicloud/src/test/resources/huawei_test.json

Osc service

---

modules/api/src/main/java/org/eclipse/osc/modules/api/OrchestratorApi.java
modules/api/src/test/java/org/eclipse/osc/modules/api/OrchestratorApiTest.java
modules/ocl-loader/src/main/java/org/eclipse/osc/modules/ocl/loader/OclResource.java
modules/ocl-loader/src/main/java/org/eclipse/osc/modules/ocl/loader/OclResources.java
modules/orchestrator/src/main/java/org/eclipse/osc/orchestrator/OrchestratorService.java

Add state api

---

plugins/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/BuilderContext.java
plugins/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/FileOrchestratorStorage.java
plugins/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/HuaweiCloudOrchestratorPlugin.java
plugins/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/HuaweiImageBuilder.java
plugins/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/HuaweiResourceBuilder.java
plugins/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/terraform/Ocl2Hcl.java
plugins/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/terraform/OclTFExecutor.java
plugins/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/terraform/TFResources.java
plugins/huaweicloud/src/main/resources/META-INF/services/org.apache.karaf.minho.boot.spi.Service
plugins/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/terraform/OclTFExecutorTest.java
plugins/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/terraform/TFResourcesTest.java
plugins/huaweicloud/src/test/resources/tfstate.json

Expose the resources state of managedServices in huawei plugin.

---

plugins/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/HuaweiImageBuilder.java
plugins/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/packer/Ocl2Packer.java
plugins/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/terraform/Ocl2Hcl.java
plugins/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/utils/IPTool.java
plugins/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/builders/utils/IPToolTest.java

Packer fix

---

modules/ocl-loader/src/main/java/org/eclipse/xpanse/modules/ocl/loader/data/models/UserData.java
modules/ocl-loader/src/main/java/org/eclipse/xpanse/modules/ocl/loader/data/models/Vm.java
modules/ocl-loader/src/main/java/org/eclipse/xpanse/modules/ocl/loader/data/models/enums/UserDataType.java
modules/ocl-loader/src/test/resources/test.json
plugins/huaweicloud/src/test/resources/huawei_test.json

Add UserData to `data.models` for VM.
related to #122 , #116

Add UserData for VM.

---

plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/NeutronManager.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/NovaManager.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/OpenstackOrchestratorPlugin.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/UserDataHelper.java
plugins/openstack/src/test/java/org/eclipse/xpanse/orchestrator/plugin/openstack/OpenstackOrchestratorPluginIntegrationTest.java
plugins/openstack/src/test/java/org/eclipse/xpanse/orchestrator/plugin/openstack/OpenstackOrchestratorPluginTest.java
plugins/openstack/src/test/resources/kafka-test.json

Updated openstack plugin according to the new OCL "userdata" structure changes.

update openstack plugin based on new OCL structure

---

website/docs/runtime.md
website/docusaurus.config.js

Updated broken GH pages link
Updated "runtime" page.

update runtime documentation

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeployment.java

Add flavor variables to terraform-deployment.

---

ui/src/App.tsx
ui/src/components/content/catalog/Catalog.tsx
ui/src/components/content/catalog/services/ServiceDetail.tsx
ui/src/components/content/catalog/services/ServiceProvider.tsx
ui/src/components/content/catalog/services/ServiceTree.tsx
ui/src/components/content/catalog/services/catalogMenu.tsx
ui/src/components/content/home/Home.tsx
ui/src/components/content/login/LoginScreen.tsx
ui/src/components/content/register/DisplayOclData.tsx
ui/src/components/content/register/RegisterPanel.tsx
ui/src/components/content/register/registerPanelMenu.tsx
ui/src/components/content/systemStatus/SystemStatusBar.tsx
ui/src/components/layouts/header/LayoutHeader.tsx
ui/src/components/layouts/sider/LayoutSider.tsx
ui/src/components/protectedRoutes/ProtectedRoute.tsx
ui/src/components/utils/constants.tsx
ui/src/styles/app.css
ui/src/styles/catalog.css
ui/src/styles/register.css

add catalog.

---

README.md

1. Use HCL code format indentation
2. Use vps, subnets, and secgroups datasource instead
3. Get rid of dns param in subnet as it will be automatically added

Format terraform codes in README

---

modules/models/src/main/java/org/eclipse/xpanse/modules/models/enums/DeployResourceKind.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/PublicIp.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/Vm.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/Volume.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/Vpc.java
modules/orchestrator/src/test/java/org/eclipse/xpanse/orchestrator/service/impl/DatabaseDeployServiceStorageTest.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/FlexibleTerraformResourceHandler.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/HuaweiTerraformResourceHandler.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/models/HuaweiPublicIpProperty.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/models/HuaweiResourceProperty.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/models/HuaweiVmProperty.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/models/HuaweiVolumeProperty.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/models/HuaweiVpcProperty.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/OpenstackTerraformResourceHandler.java

Refine the resource Handler

---

modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/CommonExceptionHandler.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/register/impl/RegisterServiceImpl.java

Add check parameters of the update service.

---

modules/api/src/main/java/org/eclipse/xpanse/api/OrchestratorApi.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/resource/Region.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/CreateRequest.java

Minor fixes for the issues identified during client generation on UI.

fix API definitions

---

Dockerfile

provide docker image with terraform installed.

---

modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DeployServiceEntity.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/resource/TfOutput.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/resource/TfState.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/view/ServiceDetailVo.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/OrchestratorService.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/FlexibleEngineTerraformResourceHandler.java
plugins/flexibleengine/src/test/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/FlexibleEngineTerraformResourceHandlerTest.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/HuaweiTerraformResourceHandler.java
plugins/huaweicloud/src/test/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/HuaweiTerraformResourceHandlerTest.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/OpenstackTerraformResourceHandler.java
plugins/openstack/src/test/java/org/eclipse/xpanse/orchestrator/plugin/openstack/OpenstackTerraformResourceHandlerTest.java

add service output implement

---

.gitignore
README.md
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeployment.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformExecutor.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironments.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/enums/DeployVariableKind.java
modules/orchestrator/src/test/resources/ocl_testOpenApi.yaml
samples/flexibleEngine-K8S.yml
samples/flexibleEngine-Kafka.yml
samples/huawei-K8S.yml
samples/huawei-Kafka.yml
samples/openstack-Kafka.yml

load flavor properties as regular input variables

---

modules/api/src/main/java/org/eclipse/xpanse/api/OrchestratorApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/config/XpanseOpenApiConfig.java
modules/models/pom.xml
modules/models/src/main/java/org/eclipse/xpanse/modules/models/view/RegisteredServiceVo.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/register/RegisterService.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/register/impl/RegisterServiceImpl.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/utils/OpenApiUtil.java
runtime/src/main/resources/application.properties

Add Link OpenApiUrl in Registered Service View Object with HATEOS

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformExecutor.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/utils/SystemCmd.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/utils/SystemCmdResult.java

Return more information from SystemCmd and allow clients to handle errors

Refactor SystemCmd

---

modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DeployResourceEntity.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DeployServiceEntity.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/utils/EntityTransUtils.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/Deployment.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeployment.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/DeployResult.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/OrchestratorService.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/FlexibleEngineTerraformResourceHandler.java
plugins/flexibleengine/src/test/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/FlexibleEngineTerraformResourceHandlerTest.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/HuaweiTerraformResourceHandler.java
plugins/huaweicloud/src/test/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/HuaweiTerraformResourceHandlerTest.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/OpenstackTerraformResourceHandler.java
plugins/openstack/src/test/java/org/eclipse/xpanse/orchestrator/plugin/openstack/OpenstackTerraformResourceHandlerTest.java

Save TfState file and destroying build workspace

---

modules/api/src/main/java/org/eclipse/xpanse/api/OrchestratorApi.java

Refactor API URIs to have uniform pattern

---

modules/api/src/main/java/org/eclipse/xpanse/api/OrchestratorApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/CommonExceptionHandler.java
modules/api/src/main/java/org/eclipse/xpanse/api/response/Response.java
modules/api/src/main/java/org/eclipse/xpanse/api/response/ResultType.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/Deployment.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeployment.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformExecutor.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/resource/TfValidateDiagnostics.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/resource/TfValidationResult.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/exceptions/TerraformScriptFormatInvalidException.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/OrchestratorService.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/register/impl/RegisterServiceImpl.java

validate terraform script

---

modules/api/src/main/java/org/eclipse/xpanse/api/OrchestratorApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/config/CategoryEnumConverter.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/enums/Category.java

With this change, category in the requests parameters are no more a string.

use enum directly in request params

---

modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/CommonExceptionHandler.java
modules/api/src/main/java/org/eclipse/xpanse/api/response/ResponseValidator.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/OrchestratorService.java

Minor findings on response exception  handling

refactor exception handling

---

modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/register/impl/RegisterServiceImpl.java

set the value of the regions.

---

modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/OrchestratorService.java

Show properties of the deployed services on MyServices list.

---

modules/api/src/main/java/org/eclipse/xpanse/api/OrchestratorApi.java

fix URI format

---

README.md
modules/orchestrator/src/test/resources/ocl_testOpenApi.yaml
samples/flexibleEngine-K8S.yml
samples/flexibleEngine-Kafka.yml
samples/huawei-K8S.yml
samples/huawei-Kafka.yml
samples/openstack-Kafka.yml

Fix OCL samples.

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeployment.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformExecutor.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/utils/SystemCmd.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/utils/SystemCmdResult.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeploymentTest.java
runtime/src/main/resources/application-test.properties
runtime/src/main/resources/application.properties

add option to run Terraform cli with debug

---

Dockerfile
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/utils/OpenApiUtil.java
modules/orchestrator/src/test/java/org/eclipse/xpanse/orchestrator/utils/OpenApiUtilTest.java
runtime/src/main/resources/application.properties

fix generate openAPI failed.

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/utils/SystemCmd.java

fix service deployment blocking error.

---

README.md

remove not implemented information

---

modules/monitor/src/main/java/org/eclipse/xpanse/modules/monitor/enums/MetricNameEnum.java
modules/monitor/src/main/java/org/eclipse/xpanse/modules/monitor/enums/MonitorResourceType.java

Define the metric name and monitor resource type

---

modules/api/src/main/java/org/eclipse/xpanse/api/OrchestratorApi.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DeployServiceEntity.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/CreateRequest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/view/ServiceVo.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/OrchestratorService.java
runtime/src/main/resources/application.properties

store user details for deployment

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformExecutor.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/utils/SystemCmd.java

@baixinsui can you please try to test this change for terraform execution on your system?
Today, sometimes it worked and sometimes it did not. So I changed the logic again. 
Please let me know if the process hangs for your combination.

refactor terraform execution logs

---

modules/api/src/main/java/org/eclipse/xpanse/api/MonitorApi.java
modules/monitor/src/main/java/org/eclipse/xpanse/modules/monitor/MetricsExporter.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/monitor/Monitor.java
modules/orchestrator/src/test/java/org/eclipse/xpanse/orchestrator/PluginTest.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/FlexibleEngineOrchestratorPlugin.java
plugins/huaweicloud/pom.xml
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/HuaweiCloudOrchestratorPlugin.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/monitor/constant/HuaweiCloudMonitorConstants.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/monitor/models/HuaweiCloudMetric.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/monitor/models/HuaweiCloudMonitorMetrics.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/monitor/models/HuaweiCloudNameSpaceKind.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/monitor/utils/HuaweiCloudMonitorCache.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/monitor/utils/HuaweiCloudMonitorClient.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/monitor/utils/HuaweiCloudToXpanseDataModelConverter.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/OpenstackOrchestratorPlugin.java

Monitor metric

---

modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/credential/CredentialCenter.java

add get Credential Variables from the Environment.

---

modules/api/src/main/java/org/eclipse/xpanse/api/CredentialManageApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/OrchestratorApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/config/CredentialTypeEnumConverter.java
modules/api/src/main/java/org/eclipse/xpanse/api/config/CspEnumConverter.java
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/AbstractCredentialInfo.java
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CreateCredential.java
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialDefinition.java
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialVariable.java
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/enums/CredentialType.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/enums/Csp.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/credential/CredentialCenter.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/HuaweiCloudOrchestratorPlugin.java

Add credential manage APIs

---

modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialCacheKey.java
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialCacheManager.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/credential/CredentialCenter.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/FlexibleEngineOrchestratorPlugin.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/HuaweiCloudOrchestratorPlugin.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/OpenstackOrchestratorPlugin.java

@iskey @swaroopar Please review this PR.

Implement CredentialCenter methods of credential management APIs

---

modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/utils/OpenApiUtil.java
modules/orchestrator/src/test/java/org/eclipse/xpanse/orchestrator/register/impl/RegisterServiceImplTest.java
modules/orchestrator/src/test/resources/ocl_test.yaml
runtime/pom.xml
runtime/src/test/java/org/eclipse/xpanse/runtime/OrchestratorApiTest.java
runtime/src/test/resources/ocl_test.yaml

add unit test for the register and OrchestratorApi.

---

modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DatabaseDeployServiceStorage.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DeployServiceEntity.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DeployServiceStorage.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformExecutor.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/exceptions/TerraformExecutorException.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/view/ServiceDetailVo.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/OrchestratorService.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/register/impl/RegisterServiceImpl.java

@swaroopar @iskey Please review this PR.

Add failure message of the service deployment and service destruction

---

plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/HuaweiCloudOrchestratorPlugin.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/monitor/models/HuaweiCloudMonitorMetrics.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/monitor/utils/HuaweiCloudToXpanseDataModelConverter.java

Optimize the monitor plugin for Huawei Cloud (prioritize using Agent to query cpu and mem).

---

plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/monitor/MetricsService.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/monitor/constant/FlexibleEngineMonitorConstants.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/monitor/models/FlexibleEngineMonitorMetrics.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/monitor/utils/FlexibleEngineMonitorConverter.java

Optimize the monitor plugin for FlexibleEngine (prioritize using Agent to query cpu and mem)

---

modules/database/src/main/java/org/eclipse/xpanse/modules/database/register/DatabaseRegisterServiceStorage.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/resource/DatabaseDeployResourceStorage.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DatabaseDeployServiceStorage.java

fix db error when destroying services

---

modules/database/src/main/java/org/eclipse/xpanse/modules/database/resource/DatabaseDeployResourceStorage.java
modules/monitor/src/main/java/org/eclipse/xpanse/modules/monitor/MetricRequest.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/monitor/Monitor.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/monitor/utils/FlexibleEngineMonitorConverter.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/monitor/utils/HuaweiCloudToXpanseDataModelConverter.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/OpenstackOrchestratorPlugin.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/monitor/gnocchi/api/AggregationService.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/monitor/gnocchi/api/MeasuresService.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/monitor/gnocchi/api/utils/MetricsQueryBuilder.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/monitor/gnocchi/models/filter/MetricsFilter.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/monitor/gnocchi/models/measures/Measure.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/monitor/keystone/KeystoneManager.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/monitor/utils/GnocchiToXpanseModelConverter.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/monitor/utils/MetricsManager.java
plugins/openstack/src/test/java/org/eclipse/xpanse/orchestrator/plugin/openstack/OpenstackOrchestratorPluginTest.java

add filters to openstack metrics

---

modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/AbstractCredentialInfo.java
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CreateCredential.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/credential/CredentialCenter.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/utils/CredentialApiUtil.java
runtime/src/test/java/org/eclipse/xpanse/runtime/CredentialManageApiTest.java

fix credential userName not used consistently

---

modules/deployment/pom.xml
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/Deployment.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeployment.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironments.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeploymentTest.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/OrchestratorService.java
modules/orchestrator/src/test/java/org/eclipse/xpanse/orchestrator/register/impl/RegisterServiceImplTest.java

return error when exception occurs

---

modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialVariable.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/credential/CredentialCenter.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/OpenstackOrchestratorPlugin.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/constants/OpenstackEnvironmentConstants.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/monitor/keystone/KeystoneManager.java

allow optional credential variables

---

modules/database/src/main/java/org/eclipse/xpanse/modules/database/resource/DeployResourceEntity.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DeployServiceEntity.java
runtime/src/main/resources/application.properties

Service entity is returning duplicate deployed resources

---

plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/monitor/HuaweiCloudMetricsService.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/monitor/models/HuaweiCloudMonitorMetrics.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/monitor/utils/HuaweiCloudToXpanseDataModelConverter.java

implement monitor metrics of Vm_network for HuaweiCloud

---

plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/monitor/MetricsService.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/monitor/models/FlexibleEngineMonitorMetrics.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/monitor/utils/FlexibleEngineMonitorConverter.java

implement monitor metrics of Vm_network for FlexibleEngine

---

modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/AbstractCredentialInfo.java

Fix Credential Schema for API.

---

modules/api/src/main/java/org/eclipse/xpanse/api/MonitorApi.java

remove method getMetricTypes

---

plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/monitor/HuaweiCloudMetricsService.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/monitor/models/HuaweiCloudRetryStrategy.java

Configure the request retry policy after calling Huawei Cloud SDK traffic restriction

---

plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/monitor/gnocchi/api/ResourcesService.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/monitor/gnocchi/models/metrics/CeilometerMetricType.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/monitor/gnocchi/models/resources/InstanceNetworkResource.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/monitor/gnocchi/models/resources/InstanceResource.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/monitor/utils/GnocchiToXpanseModelConverter.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/monitor/utils/MetricsManager.java
plugins/openstack/src/test/java/org/eclipse/xpanse/orchestrator/plugin/openstack/OpenstackMonitoringIntegrationTest.java
plugins/openstack/src/test/resources/mappings/instance_network_interface_resources.json

add network metrics for openstack instances

---

modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialVariable.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/FlexibleEngineOrchestratorPlugin.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/HuaweiCloudOrchestratorPlugin.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/OpenstackOrchestratorPlugin.java
plugins/openstack/src/test/java/org/eclipse/xpanse/orchestrator/plugin/openstack/OpenstackMonitoringIntegrationTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/CredentialManageApiTest.java

add isSensitive field to CredentialVariable

---

modules/api/src/main/java/org/eclipse/xpanse/api/MonitorApi.java
modules/monitor/src/main/java/org/eclipse/xpanse/modules/monitor/MetricRequest.java
modules/monitor/src/main/java/org/eclipse/xpanse/modules/monitor/ResourceMetricRequest.java
modules/monitor/src/main/java/org/eclipse/xpanse/modules/monitor/ServiceMetricRequest.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/monitor/Monitor.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/monitor/MetricsService.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/monitor/utils/FlexibleEngineMonitorConverter.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/monitor/HuaweiCloudMetricsService.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/monitor/utils/HuaweiCloudToXpanseDataModelConverter.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/OpenstackOrchestratorPlugin.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/monitor/utils/GnocchiToXpanseModelConverter.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/monitor/utils/MetricsManager.java
plugins/openstack/src/test/java/org/eclipse/xpanse/orchestrator/plugin/openstack/OpenstackMonitoringIntegrationTest.java

add onlyLastKnownMetric query parameter

---

modules/api/src/main/java/org/eclipse/xpanse/api/CredentialManageApi.java
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/AbstractCredentialInfo.java
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialCacheManager.java
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialVariables.java
modules/monitor/src/main/java/org/eclipse/xpanse/modules/monitor/MetricRequest.java
modules/monitor/src/main/java/org/eclipse/xpanse/modules/monitor/ResourceMetricRequest.java
modules/monitor/src/main/java/org/eclipse/xpanse/modules/monitor/ServiceMetricRequest.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/credential/CredentialCenter.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/monitor/Monitor.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/utils/CredentialApiUtil.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/FlexibleEngineOrchestratorPlugin.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/monitor/MetricsService.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/HuaweiCloudOrchestratorPlugin.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/monitor/HuaweiCloudMetricsService.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/OpenstackOrchestratorPlugin.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/monitor/keystone/KeystoneManager.java
plugins/openstack/src/test/java/org/eclipse/xpanse/orchestrator/plugin/openstack/OpenstackMonitoringIntegrationTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/CredentialManageApiTest.java

Rename CredentialDefinition to CredentialVariables.

---

modules/api/src/main/java/org/eclipse/xpanse/api/CredentialManageApi.java
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/AbstractCredentialInfo.java
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialCacheManager.java
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialVariables.java
modules/monitor/src/main/java/org/eclipse/xpanse/modules/monitor/MetricRequest.java
modules/monitor/src/main/java/org/eclipse/xpanse/modules/monitor/ResourceMetricRequest.java
modules/monitor/src/main/java/org/eclipse/xpanse/modules/monitor/ServiceMetricRequest.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/credential/CredentialCenter.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/monitor/Monitor.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/monitor/MetricsService.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/monitor/HuaweiCloudMetricsService.java
plugins/openstack/src/main/java/org/eclipse/xpanse/orchestrator/plugin/openstack/monitor/keystone/KeystoneManager.java
runtime/src/test/java/org/eclipse/xpanse/runtime/CredentialManageApiTest.java

Fix wrong type usage for credentials.

---

modules/api/src/main/java/org/eclipse/xpanse/api/CredentialManageApi.java
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialCacheManager.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/credential/CredentialCenter.java
runtime/src/test/java/org/eclipse/xpanse/runtime/CredentialManageApiTest.java

delete credentials only for specific type

---

modules/monitor/src/main/java/org/eclipse/xpanse/modules/monitor/ResourceMetricRequest.java
plugins/flexibleengine/pom.xml
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/monitor/MetricsService.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/monitor/utils/FlexibleEngineMonitorCache.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/monitor/utils/RetryTemplateService.java
plugins/flexibleengine/src/test/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/FlexibleEngineOrchestratorPluginTest.java
runtime/src/main/resources/application.properties

RestTemplate add Spring-retry and config log output

---

plugins/huaweicloud/src/main/java/org/eclipse/xpanse/orchestrator/plugin/huaweicloud/monitor/HuaweiCloudMetricsService.java

update the value of the csp of the HuaweiCloudMetricsService.

---

modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/credential/CredentialCenter.java

update getCredentials method

---

modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/enums/CredentialTypeMessage.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/credential/CredentialCenter.java

add CredentialValue.

---

modules/api/src/main/java/org/eclipse/xpanse/api/CredentialManageApi.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/credential/CredentialCenter.java

add getCredentialsByUser method

---

modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/AbstractCredentialInfo.java
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialVariables.java
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/config/CredentialVariableDeserializer.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/exceptions/CredentialVariablesNotComplete.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/credential/CredentialCenter.java

add credential completeness validation

---

modules/api/src/main/java/org/eclipse/xpanse/api/MonitorApi.java
modules/monitor/src/main/java/org/eclipse/xpanse/modules/monitor/Monitor.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/monitor/MetricsExporter.java
modules/orchestrator/src/test/java/org/eclipse/xpanse/modules/orchestrator/PluginTest.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/FlexibleEngineOrchestratorPlugin.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/MetricsService.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/HuaweiCloudOrchestratorPlugin.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/OpenstackOrchestratorPlugin.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/monitor/utils/MetricsManager.java
plugins/openstack/src/test/java/org/eclipse/xpanse/plugins/openstack/OpenstackMonitoringIntegrationTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/MonitorApiTest.java

delete old getMetrics method

---

modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialCenter.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/credential/CredentialVariable.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/credential/config/CredentialVariableDeserializer.java

fix CredentialVariable class serialization error

---

modules/api/src/main/java/org/eclipse/xpanse/api/CredentialManageApi.java
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialCenter.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/credential/CredentialVariables.java

fix CredentialApi

---

modules/models/src/main/java/org/eclipse/xpanse/modules/models/monitor/exceptions/ClientApiCalledException.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/MetricsService.java

fix the exception thrown from client of FlexibleEngine

---

plugins/flexibleengine/src/test/java/org/eclipse/xpanse/plugins/flexibleengine/FlexibleEngineOrchestratorPluginTest.java
plugins/huaweicloud/src/test/java/org/eclipse/xpanse/plugins/huaweicloud/HuaweiCloudOrchestratorPluginTest.java
plugins/openstack/src/test/java/org/eclipse/xpanse/plugins/openstack/OpenstackOrchestratorPluginTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceRegisterApiTest.java

Rename OrchestratorApiTest and add credentialsTest for plugins

---

.gitignore
modules/common/pom.xml
modules/common/src/main/java/org/eclipse/xpanse/common/openapi/OpenApiUtil.java
modules/credential/pom.xml
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialCenter.java
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialOpenApiGenerator.java
modules/register/pom.xml
modules/register/src/main/java/org/eclipse/xpanse/modules/register/register/impl/RegisterServiceImpl.java
modules/register/src/main/java/org/eclipse/xpanse/modules/register/register/utils/RegisteredServicesOpenApiGenerator.java
modules/register/src/test/java/org/eclipse/xpanse/modules/register/OpenApiUtilTest.java
modules/register/src/test/java/org/eclipse/xpanse/modules/register/register/impl/RegisterServiceImplTest.java
pom.xml
runtime/pom.xml
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceRegisterApiTest.java

add common module

---

modules/models/src/main/java/org/eclipse/xpanse/modules/models/monitor/Metric.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/utils/FlexibleEngineMonitorConverter.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/monitor/utils/HuaweiCloudToXpanseDataModelConverter.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/monitor/utils/GnocchiToXpanseModelConverter.java

add monitorResourceType variable to monitor return resource

---

.github/workflows/ci.yml
.github/workflows/release.yml
README.md

update job names

---

modules/api/src/main/java/org/eclipse/xpanse/api/CredentialManageApi.java
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialCenter.java
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialsStore.java
modules/credential/src/test/java/org/eclipse/xpanse/modules/credential/CredentialCacheTests.java
runtime/src/test/java/org/eclipse/xpanse/runtime/CredentialManageApiTest.java

fix cred return type and uri

---

checkstyle.xml
modules/api/src/main/java/org/eclipse/xpanse/api/MonitorApi.java
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialOpenApiGenerator.java
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/cache/CaffeineCredentialCacheManager.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/register/DatabaseRegisterServiceStorage.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/resource/DatabaseDeployResourceStorage.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DeployServiceRepository.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/utils/SystemCmd.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironments.java
modules/monitor/src/main/java/org/eclipse/xpanse/modules/monitor/Monitor.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/utils/MetricsService.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/monitor/models/HuaweiCloudRetryStrategy.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/monitor/gnocchi/api/BaseGnocchiServices.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/monitor/keystone/CustomEndPointResolver.java

enable new checkstyle rules

---

modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/CredentialsExceptionHandler.java
modules/credential/pom.xml
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialCenter.java
modules/credential/src/test/java/org/eclipse/xpanse/modules/credential/CredentialSearchTests.java
modules/credential/src/test/java/org/eclipse/xpanse/modules/credential/PluginTest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/credential/exceptions/CredentialCapabilityNotFound.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/credential/exceptions/CredentialVariablesNotComplete.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/response/ResultType.java

implement credential joining for monitoring and deployment

---

modules/models/src/test/java/org/eclipse/xpanse/modules/models/admin/SystemStatusTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/admin/enums/HealthStatusTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/register/OclTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/register/exceptions/TerraformScriptFormatInvalidExceptionTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/utils/CidrValidatorTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/utils/DeployVariableValidatorTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/utils/OclLoaderTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/view/RegisteredServiceVoTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/view/ServiceDetailVoTest.java

add unit tesets for the admin package and service package under models

---

pom.xml

Fix to remove this security finding - https://github.com/eclipse-xpanse/xpanse/security/dependabot/1

remove unused dependency

---

.github/workflows/coverage.yml
README.md
pom.xml
runtime/pom.xml

coverage-test

---

modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialCenter.java

GET to return only from cache

---

plugins/flexibleengine/pom.xml
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/models/FlexibleEngineNameSpaceKind.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/utils/MetricsService.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/utils/RetryTemplateService.java
plugins/flexibleengine/src/test/java/org/eclipse/xpanse/plugins/flexibleengine/FlexibleEngineMonitorTest.java
plugins/flexibleengine/src/test/java/org/eclipse/xpanse/plugins/flexibleengine/models/FlexibleEngineResourcePropertyTest.java
plugins/flexibleengine/src/test/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/models/FlexibleEngineNameSpaceKindTest.java
plugins/flexibleengine/src/test/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/utils/MetricsServiceTest.java
plugins/flexibleengine/src/test/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/utils/RetryTemplateServiceTest.java
plugins/flexibleengine/src/test/resources/mappings/batch_query_metric_data.json
plugins/flexibleengine/src/test/resources/mappings/query_metric_data_cpu.json
plugins/flexibleengine/src/test/resources/mappings/query_metric_data_mem_usedPercent.json
plugins/flexibleengine/src/test/resources/mappings/query_metric_data_net_bitRecv.json
plugins/flexibleengine/src/test/resources/mappings/query_metric_data_net_bitSent.json
plugins/flexibleengine/src/test/resources/mappings/query_metrics_list.json
plugins/flexibleengine/src/test/resources/mappings/query_project_info.json
plugins/flexibleengine/src/test/resources/results/batch_query_metric_data.json
plugins/flexibleengine/src/test/resources/results/query_metric_data_cpu.json
plugins/flexibleengine/src/test/resources/results/query_metric_data_mem.json
plugins/flexibleengine/src/test/resources/results/query_metric_data_net_in.json
plugins/flexibleengine/src/test/resources/results/query_metric_data_net_out.json
plugins/flexibleengine/src/test/resources/results/query_metrics_list.json
plugins/flexibleengine/src/test/resources/results/query_project_info.json

add code unit tests for the module plugins/flexibleengine

---

README.md
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialCenter.java
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialOpenApiGenerator.java
modules/credential/src/test/java/org/eclipse/xpanse/modules/credential/CredentialSearchTests.java
modules/credential/src/test/java/org/eclipse/xpanse/modules/credential/DummyPluginImpl.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/OrchestratorPlugin.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/PluginManager.java
modules/orchestrator/src/test/java/org/eclipse/xpanse/modules/orchestrator/DummyFlexibleEnginePluginImpl.java
modules/orchestrator/src/test/java/org/eclipse/xpanse/modules/orchestrator/DummyOpenstackPluginImpl.java
modules/orchestrator/src/test/java/org/eclipse/xpanse/modules/orchestrator/PluginManagerTest.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/FlexibleEngineOrchestratorPlugin.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/constant/FlexibleEngineMonitorConstants.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/HuaweiCloudOrchestratorPlugin.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/OpenstackOrchestratorPlugin.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/constants/OpenstackEnvironmentConstants.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/monitor/keystone/KeystoneManager.java
plugins/openstack/src/test/java/org/eclipse/xpanse/plugins/openstack/OpenstackMonitoringIntegrationTest.java
plugins/openstack/src/test/java/org/eclipse/xpanse/plugins/openstack/OpenstackOrchestratorPluginTest.java

Add option to define mandatory configuration properties for plugins

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/utils/SystemCmd.java

update log output in Systemcmd

---

modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialCenter.java

fix cache query when optional query parameters are missing

---

modules/models/src/test/java/org/eclipse/xpanse/modules/models/admin/SystemStatusTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/common/exceptions/ResponseInvalidExceptionTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/credential/AbstractCredentialInfoTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/credential/CreateCredentialTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/credential/CredentialVariableTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/credential/CredentialVariablesTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/credential/config/CredentialVariableDeserializerTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/credential/enums/CredentialTypeMessageTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/credential/exceptions/CredentialCapabilityNotFoundTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/credential/exceptions/CredentialVariablesNotCompleteTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/credential/exceptions/CredentialsNotFoundExceptionTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/credential/exceptions/NoCredentialDefinitionAvailableTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/monitor/exceptions/ClientApiCallFailedExceptionTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/deploy/CreateRequestTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/deploy/DeployResourceTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/deploy/DeployResultTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/deploy/PublicIpTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/deploy/VmTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/deploy/VolumeTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/deploy/VpcTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/deploy/enums/DeployResourceKindTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/deploy/enums/ServiceStateTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/deploy/enums/TerraformExecStateTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/deploy/enums/VariableValidatorTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/view/RegisteredServiceVoTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/view/ServiceDetailVoTest.java

add tests of models module

---

README.md
modules/database/pom.xml
modules/database/src/test/java/org/eclipse/xpanse/modules/database/service/DatabaseDeployServiceStorageTest.java
modules/register/src/main/java/org/eclipse/xpanse/modules/register/register/utils/RegisteredServicesOpenApiGenerator.java
runtime/pom.xml
runtime/src/main/resources/application-huaweicloud.properties
runtime/src/main/resources/application-mariadb.properties
runtime/src/main/resources/application-openstack.properties
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceRegisterApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/database/mariadb/AbstractMariaDbIntegrationTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/database/mariadb/DeploymentWithMariaDbTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/database/mariadb/RegistrationWithMariaDbTest.java
runtime/src/test/resources/ocl_test_dummy.yaml

add mariadb support

---

modules/orchestrator/src/test/java/org/eclipse/xpanse/modules/orchestrator/deployment/DeployTaskTest.java
modules/orchestrator/src/test/java/org/eclipse/xpanse/modules/orchestrator/deployment/DeployValidateDiagnosticsTest.java
modules/orchestrator/src/test/java/org/eclipse/xpanse/modules/orchestrator/deployment/DeployValidationResultTest.java
modules/orchestrator/src/test/java/org/eclipse/xpanse/modules/orchestrator/monitor/MetricRequestTest.java
modules/orchestrator/src/test/java/org/eclipse/xpanse/modules/orchestrator/monitor/ResourceMetricRequestTest.java
modules/orchestrator/src/test/java/org/eclipse/xpanse/modules/orchestrator/monitor/ServiceMetricRequestTest.java

Add tests to increase test coverage of Orchestrator module

---

modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/RegistrationExceptionHandler.java
modules/api/src/test/java/org/eclipse/xpanse/api/RegistrationExceptionHandlerTests.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/register/DatabaseRegisterServiceStorage.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/response/ResultType.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/register/exceptions/ServiceUpdateNotAllowed.java
modules/register/src/main/java/org/eclipse/xpanse/modules/register/register/impl/RegisterServiceImpl.java
runtime/pom.xml

add new custom exception

---

modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/DeploymentExceptionHandler.java
modules/api/src/test/java/org/eclipse/xpanse/api/DeploymentExceptionHandlerTests.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/response/ResultType.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/deploy/exceptions/InvalidDeploymentVariableException.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/utils/DeployVariableValidator.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/utils/DeployVariableValidatorTest.java

add new custom exception for deployment variables validation

---

plugins/openstack/src/test/java/org/eclipse/xpanse/plugins/openstack/OpenstackMonitoringIntegrationTest.java
plugins/openstack/src/test/java/org/eclipse/xpanse/plugins/openstack/OpenstackOrchestratorPluginTest.java
plugins/openstack/src/test/java/org/eclipse/xpanse/plugins/openstack/monitor/gnocchi/models/filter/MetricsFilterTest.java
plugins/openstack/src/test/java/org/eclipse/xpanse/plugins/openstack/monitor/gnocchi/models/measures/MeasureTest.java
plugins/openstack/src/test/java/org/eclipse/xpanse/plugins/openstack/monitor/gnocchi/models/resources/InstanceNetworkResourceTest.java
plugins/openstack/src/test/java/org/eclipse/xpanse/plugins/openstack/monitor/gnocchi/models/resources/InstanceResourceTest.java
plugins/openstack/src/test/resources/openstack-tfstate.json
runtime/src/test/java/org/eclipse/xpanse/runtime/database/mariadb/DeploymentWithMariaDbTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/database/mariadb/RegistrationWithMariaDbTest.java

Add tests to increase test coverage of Openstack plugin

---

modules/logging/src/test/java/org/eclipse/xpanse/modules/logging/CustomHttpLogFormatterTest.java
modules/logging/src/test/java/org/eclipse/xpanse/modules/logging/CustomRequestIdGeneratorTest.java

Add tests to increase test coverage of Logging module

---

modules/database/src/test/java/org/eclipse/xpanse/modules/database/common/CreateModifiedTimeTest.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/common/ObjectJsonConverterTest.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/register/DatabaseRegisterServiceStorageTest.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/register/RegisterServiceEntityTest.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/resource/DatabaseDeployResourceStorageTest.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/resource/DeployResourceEntityTest.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/service/DatabaseDeployServiceStorageTest.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/service/DeployServiceEntityTest.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/utils/EntityTransUtilsTest.java
modules/database/src/test/resources/ocl_test.yaml

Add tests to increase test coverage of database module

---

modules/api/src/main/java/org/eclipse/xpanse/api/ServiceDeployerApi.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/view/UserAvailableServiceVo.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/view/UserAvailableServiceVoTest.java
modules/register/src/main/java/org/eclipse/xpanse/modules/register/register/impl/RegisterServiceImpl.java

display credential type in register, update and catalog UI

---

modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/DeployServiceTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/async/ServiceThreadPoolTaskExecutorTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/async/TaskConfigurationTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/async/ThreadMdcUtilTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeploymentTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformProvidersTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/providers/AwsTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/providers/FlexibleEngineTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/providers/HuaweiTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/providers/OpenstackTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/resource/TfOutputTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/resource/TfStateResourceInstanceTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/resource/TfStateResourceTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/resource/TfStateTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/utils/SystemCmdResultTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/utils/SystemCmdTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/utils/TfResourceTransUtilsTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironmentsTest.java

add test for deployment module

---

modules/api/pom.xml
modules/models/pom.xml
pom.xml

update framework versions

---

modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialCenter.java
modules/credential/src/test/java/org/eclipse/xpanse/modules/credential/CredentialCenterTest.java

fix error in cache when masked isSensitive fields

---

modules/api/pom.xml
modules/api/src/test/java/org/eclipse/xpanse/api/CommonExceptionHandlerTests.java
modules/api/src/test/java/org/eclipse/xpanse/api/CredentialsExceptionHandlerTests.java
modules/api/src/test/java/org/eclipse/xpanse/api/DeploymentExceptionHandlerTests.java
modules/api/src/test/java/org/eclipse/xpanse/api/MonitoringExceptionHandlerTests.java
modules/api/src/test/java/org/eclipse/xpanse/api/RegistrationExceptionHandlerTests.java
modules/common/pom.xml
modules/common/src/main/java/org/eclipse/xpanse/common/security/config/SensitiveFieldEncoderConfig.java
runtime/src/main/java/org/eclipse/xpanse/runtime/XpanseApplication.java
runtime/src/test/java/org/eclipse/xpanse/runtime/modules/common/SensitiveFieldEncoderConfigTest.java

Add pbkdf2 + spring security for sensitive field

---

modules/api/src/main/java/org/eclipse/xpanse/api/config/SpringDocOpenApiConfig.java

Config SpringDoc openAPI Info

---

README.md
modules/pom.xml
modules/security/pom.xml
modules/security/src/main/java/org/eclipse/xpanse/modules/security/config/ZitadelOpenApiOauth2Config.java
modules/security/src/main/java/org/eclipse/xpanse/modules/security/config/ZitadelWebSecurityConfig.java
runtime/pom.xml
runtime/src/main/java/org/eclipse/xpanse/runtime/XpanseApplication.java
runtime/src/main/resources/application-zitadel-testbed.properties
runtime/src/main/resources/application-zitadel.properties

enable spring security oauth2 on api-client and swagger-ui

---

.github/workflows/release.yml

fixes #582 
Images are found here - https://github.com/orgs/eclipse-xpanse/packages

add steps to build and release image to github packages

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/providers/Huawei.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/providers/HuaweiTest.java
modules/security/src/main/java/org/eclipse/xpanse/modules/security/config/ZitadelWebSecurityConfig.java

allow preflight requests from browser.

enable CORS in security filter

---

modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialOpenApiGenerator.java
runtime/src/test/java/org/eclipse/xpanse/runtime/modules/credential/CredentialOpenApiGeneratorTest.java

fix app startup crashes with openapi file generation fails

---

modules/api/src/test/java/org/eclipse/xpanse/api/CommonExceptionHandlerTests.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/security/model/TokenResponseTest.java
modules/security/pom.xml
modules/security/src/test/java/org/eclipse/xpanse/modules/security/zitadel/introspector/ZitadelAuthoritiesOpaqueTokenIntrospectorTest.java
modules/security/src/test/resources/mappings/oauth_v2_introspector.json
runtime/pom.xml
runtime/src/test/java/org/eclipse/xpanse/runtime/CredentialManageApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/MonitorApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceRegisterApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ZitadelAuthorizationApiTest.java
runtime/src/test/resources/mappings/oauth_v2_token.json

Add tests to increase test coverage of security module

---

modules/logging/pom.xml
plugins/flexibleengine/pom.xml
plugins/huaweicloud/pom.xml
plugins/openstack/pom.xml

remove commons-logging from dependency.

---

README.md
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/Provider.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeployment.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformVersionProvider.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/providers/Aws.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/providers/FlexibleEngine.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/providers/Huawei.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/providers/Openstack.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeploymentTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/providers/AwsTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/providers/FlexibleEngineTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/providers/HuaweiTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/providers/OpenstackTest.java
modules/register/src/test/java/org/eclipse/xpanse/modules/register/register/impl/RegisterServiceImplTest.java
runtime/src/main/resources/application.properties

Make terraform provider version a configurable property

---

modules/security/src/main/java/org/eclipse/xpanse/modules/security/zitadel/config/ZitadelWebSecurityConfig.java

fix opening service openAPI fails with 401

---

modules/api/src/main/java/org/eclipse/xpanse/api/AdminServicesApi.java
modules/security/src/main/java/org/eclipse/xpanse/modules/security/zitadel/config/RequiredRoleDescriptionCustomizer.java

Display of roles required for a service in Swagger-UI

---

modules/common/src/test/java/org/eclipse/xpanse/common/openapi/OpenApiUtilTest.java
modules/security/src/test/java/org/eclipse/xpanse/modules/security/config/AesUtilTest.java
modules/security/src/test/resources/aes_sec_test

add test for OpenApiUtil and AesUtil

---

README.md

remove empty lines

---

modules/security/src/main/java/org/eclipse/xpanse/modules/security/zitadel/config/ZitadelWebSecurityConfig.java

fix open h2-console error when oauth2 is enabled

---

modules/security/src/main/java/org/eclipse/xpanse/modules/security/zitadel/ZitadelAuthorizationService.java

fix identity provider status error

---

modules/api/src/main/java/org/eclipse/xpanse/api/ServiceRegisterApi.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceRegisterApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ZitadelAuthorizationApiTest.java

remove listCategories method

---

modules/api/src/main/java/org/eclipse/xpanse/api/ServiceDeployerApi.java

fix wrong documentation of mandatory field

---

modules/api/src/main/java/org/eclipse/xpanse/api/ServiceCatalogApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/ServiceDeployerApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/ServiceRegisterApi.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java

Split catalog API methods to ServiceCatalogApi

---

modules/api/src/main/java/org/eclipse/xpanse/api/AdminServicesApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/CredentialManageApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/MonitorApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/ServiceCatalogApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/ServiceRegisterApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/ZitadelAuthorizationApi.java

update API documentation

---

modules/api/src/main/java/org/eclipse/xpanse/api/CredentialManageApi.java
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialCenter.java
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialsStore.java
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/cache/CredentialCacheKey.java
modules/credential/src/test/java/org/eclipse/xpanse/modules/credential/CredentialCacheTests.java
modules/credential/src/test/java/org/eclipse/xpanse/modules/credential/CredentialCenterTest.java
modules/credential/src/test/java/org/eclipse/xpanse/modules/credential/CredentialSearchTests.java
modules/credential/src/test/java/org/eclipse/xpanse/modules/credential/DummyPluginImpl.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironments.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironmentsTest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/credential/AbstractCredentialInfo.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/credential/exceptions/DuplicateCredentialDefinition.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/PluginManager.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/FlexibleEngineOrchestratorPlugin.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/utils/MetricsService.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/HuaweiCloudOrchestratorPlugin.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/monitor/utils/HuaweiCloudMetricsService.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/OpenstackOrchestratorPlugin.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/monitor/utils/MetricsManager.java
runtime/src/test/java/org/eclipse/xpanse/runtime/CredentialManageApiTest.java

fix query credentials of user return duplicate data

---

Dockerfile

AES key generation for docker image

---

modules/register/src/main/java/org/eclipse/xpanse/modules/register/register/impl/RegisterServiceImpl.java
modules/register/src/test/java/org/eclipse/xpanse/modules/register/register/impl/RegisterServiceImplTest.java

ServiceCatalogApi- fix the links attribute return empty

---

modules/database/src/main/java/org/eclipse/xpanse/modules/database/register/DatabaseRegisterServiceStorage.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/register/DatabaseRegisterServiceStorageTest.java

ServiceCatalogApi- fix availableServiceDetails method return empty object when the incoming ID is incorrect

---

modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/CommonExceptionHandler.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/common/exceptions/UnsupportedEnumValueException.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/response/ResultType.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/common/enums/Category.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/common/enums/Csp.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/common/enums/CategoryTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/common/enums/CspTest.java

fix deserialization bugs for unsupported enumerate values

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironments.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironmentsTest.java

fix bug in get credential during deployment

---

modules/security/src/main/java/org/eclipse/xpanse/modules/security/zitadel/common/ZitadelUserAuthenticationConverter.java

fix bug- HealthCheck API fails with null pointer

---

modules/security/src/main/java/org/eclipse/xpanse/modules/security/zitadel/config/RequiredRoleDescriptionCustomizer.java
modules/security/src/main/java/org/eclipse/xpanse/modules/security/zitadel/config/ZitadelWebSecurityConfig.java

fix POST API return 403 when Unauthorized

---

samples/huawei-Kafka-terraform_module.yml

Add and use terraform_ module sample Service registration file

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformExecutor.java

handle space in terraform variable values

---

plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/utils/FlexibleEngineMetricsService.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/monitor/utils/HuaweiCloudMetricsService.java

fix monitor query sends null pointer for HuaweiCloud and FlexibleEngine

---

modules/api/src/main/java/org/eclipse/xpanse/api/AdminServicesApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/ServiceCatalogApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/ServiceRegisterApi.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/security/constant/RoleConstants.java

Add ROLE_ISV and replace the usage of the ROLE_CSP to ROLE_ISV.

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformExecutor.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeploymentTest.java

use terraform vars file

---

modules/api/src/main/java/org/eclipse/xpanse/api/ServiceDeployerApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/handler/DeploymentExceptionHandler.java
modules/api/src/test/java/org/eclipse/xpanse/api/exceptions/handler/DeploymentExceptionHandlerTest.java
modules/api/src/test/java/org/eclipse/xpanse/api/exceptions/handler/RegistrationExceptionHandlerTest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/DeployServiceTest.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/utils/ServiceTemplateOpenApiGenerator.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/monitor/utils/HuaweiCloudMetricsService.java
plugins/huaweicloud/src/test/java/org/eclipse/xpanse/plugins/huaweicloud/monitor/utils/HuaweiCloudMonitorClientTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/AuthorizationApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/database/mariadb/DeploymentWithMariaDbTest.java
runtime/src/test/resources/ocl_test.yaml

fixed https://github.com/eclipse-xpanse/xpanse/issues/722
related https://github.com/eclipse-xpanse/xpanse-ui/pull/157

Refactor Deploy API

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformProviders.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformVersionProvider.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/providers/Scs.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/common/enums/Csp.java
modules/pom.xml
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/constants/OpenstackEnvironmentConstants.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/monitor/keystone/KeystoneManager.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/monitor/utils/GnocchiToXpanseModelConverter.java
plugins/pom.xml
plugins/scs/pom.xml
plugins/scs/src/main/java/org/eclipse/xpanse/plugins/scs/ScsOrchestratorPlugin.java
plugins/scs/src/main/java/org/eclipse/xpanse/plugins/scs/ScsTerraformResourceHandler.java
plugins/scs/src/main/java/org/eclipse/xpanse/plugins/scs/constants/ScsEnvironmentConstants.java
plugins/scs/src/main/java/org/eclipse/xpanse/plugins/scs/enums/ScsResourceProperty.java
plugins/scs/src/test/java/org/eclipse/xpanse/plugins/scs/ScsOrchestratorPluginTest.java
plugins/scs/src/test/java/org/eclipse/xpanse/plugins/scs/ScsTerraformResourceHandlerTest.java
plugins/scs/src/test/resources/scs-tfstate-destroy.json
plugins/scs/src/test/resources/scs-tfstate.json
pom.xml
runtime/pom.xml
runtime/src/main/resources/application.properties

introduce plugin for SCS cloud

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformExecutor.java

fix terraform deploy filed caused by null value of variables

---

.github/workflows/coverage.yml
runtime/pom.xml

Disable jacoco by default,Enable only in CI pipeline

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/async/TaskConfiguration.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeployment.java
runtime/src/main/resources/application.properties

Gracefully Shutdown and Wait tasks all completed before shutting down

---

.github/workflows/release-docker-only.yml

add job to release only docker image

---

modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DatabaseDeployServiceStorage.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DeployServiceStorage.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeployment.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformExecutor.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/deployment/Deployment.java

Delete workspace of task after Saving data successfully

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeployment.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/DeployServiceTest.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/FlexibleEngineTerraformResourceHandler.java
plugins/flexibleengine/src/test/java/org/eclipse/xpanse/plugins/flexibleengine/FlexibleEngineTerraformResourceHandlerTest.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/HuaweiTerraformResourceHandler.java
plugins/huaweicloud/src/test/java/org/eclipse/xpanse/plugins/huaweicloud/HuaweiTerraformResourceHandlerTest.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/OpenstackTerraformResourceHandler.java
plugins/openstack/src/test/java/org/eclipse/xpanse/plugins/openstack/OpenstackTerraformResourceHandlerTest.java
plugins/scs/src/main/java/org/eclipse/xpanse/plugins/scs/ScsTerraformResourceHandler.java
plugins/scs/src/test/java/org/eclipse/xpanse/plugins/scs/ScsTerraformResourceHandlerTest.java

fix Openstack destroy failed.

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironments.java
plugins/scs/src/main/java/org/eclipse/xpanse/plugins/scs/ScsOrchestratorPlugin.java
plugins/scs/src/main/java/org/eclipse/xpanse/plugins/scs/constants/ScsEnvironmentConstants.java
plugins/scs/src/test/java/org/eclipse/xpanse/plugins/scs/ScsOrchestratorPluginTest.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/767
i will fix the website doc separately as soon as it is merged.

remove mandatory variable for SCS

---

Dockerfile

update app jar path

---

runtime/src/main/resources/application-zitadel.properties
runtime/src/main/resources/application.properties

fixed https://github.com/eclipse-xpanse/xpanse/issues/614
related https://github.com/eclipse-xpanse/xpanse-iam/pull/6

set default local service url of zitadel

---

Dockerfile
runtime/pom.xml
start-xpanse-with-private_key.sh

reduce xpanse docker image size

---

modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/deploy/enums/ServiceDeploymentState.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/deploy/enums/ServiceDeploymentStateTest.java

changing enum string values so that it can be directly used in UI/API

add user friendly enum string values

---

modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/deploy/enums/ServiceDeploymentState.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/enums/ServiceRegistrationState.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/deploy/enums/ServiceDeploymentStateTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/enums/ServiceRegistrationStateTest.java

related to https://github.com/eclipse-xpanse/xpanse/issues/799

fix enum string values

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/DeployServiceTest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/deploy/enums/ServiceDeploymentState.java

perform rollback when deployment fails

---

modules/api/src/main/java/org/eclipse/xpanse/api/ServiceDeployerApi.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DatabaseDeployServiceStorage.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DeployServiceStorage.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/service/DatabaseDeployServiceStorageTest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/DeployServiceTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java

add purge API method

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/ApiClient.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/JavaTimeFormatter.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/api/TerraformApi.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/auth/ApiKeyAuth.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/auth/HttpBasicAuth.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/auth/HttpBearerAuth.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/model/Response.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/model/TerraformAsyncDeployRequest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/model/TerraformAsyncDestroyRequest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/model/TerraformBootSystemStatus.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/model/TerraformDeployRequest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/model/TerraformDestroyRequest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/model/TerraformResult.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/model/TerraformValidateDiagnostics.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/model/TerraformValidationResult.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/model/WebhookConfig.java
modules/deployment/src/main/resources/terraformbootApi.json

Generating new data models for terraform-boot

---

modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java

update validation error message.

change error message for update validation

---

modules/api/src/main/java/org/eclipse/xpanse/api/AdminServicesApi.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicetemplate/ServiceTemplateEntity.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/servicetemplate/ServiceTemplateEntityTest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/security/model/CurrentUserInfo.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/view/ServiceTemplateVo.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/security/model/CurrentUserInfoTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/view/ServiceTemplateVoTest.java
modules/security/src/main/java/org/eclipse/xpanse/modules/security/zitadel/ZitadelIdentityProviderService.java
modules/security/src/main/java/org/eclipse/xpanse/modules/security/zitadel/config/ZitadelOauth2Constant.java
modules/security/src/main/java/org/eclipse/xpanse/modules/security/zitadel/config/ZitadelOpenApiOauth2Config.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java
modules/servicetemplate/src/test/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManageTest.java

fixed https://github.com/eclipse-xpanse/xpanse/issues/792
related https://github.com/eclipse-xpanse/xpanse-ui/pull/183

Get metadata of user and Add namespace in ServiceTemplate

---

modules/api/src/main/java/org/eclipse/xpanse/api/ServiceCatalogApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/ServiceTemplateApi.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceTemplateApiTest.java

fixed https://github.com/eclipse-xpanse/xpanse/issues/823
related https://github.com/eclipse-xpanse/xpanse-ui/pull/185

Update listServiceTemplates API

---

modules/api/pom.xml
modules/common/pom.xml
modules/credential/pom.xml
modules/database/pom.xml
modules/deployment/pom.xml
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/ApiClient.java
modules/monitor/pom.xml
modules/security/pom.xml
modules/security/src/main/java/org/eclipse/xpanse/modules/security/zitadel/config/ZitadelWebSecurityConfig.java
modules/security/src/test/java/org/eclipse/xpanse/modules/security/zitadel/introspector/ZitadelOpaqueTokenIntrospectorTest.java
modules/servicetemplate/pom.xml
plugins/flexibleengine/pom.xml
plugins/flexibleengine/src/test/java/org/eclipse/xpanse/plugins/flexibleengine/FlexibleEngineMonitorIntegrationTest.java
plugins/flexibleengine/src/test/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/utils/RetryTemplateServiceTest.java
plugins/huaweicloud/pom.xml
plugins/huaweicloud/src/test/java/org/eclipse/xpanse/plugins/huaweicloud/HuaweiCloudMonitorIntegrationTest.java
plugins/openstack/pom.xml
plugins/openstack/src/test/java/org/eclipse/xpanse/plugins/openstack/OpenstackMonitoringIntegrationTest.java
plugins/openstack/src/test/java/org/eclipse/xpanse/plugins/openstack/OpenstackTerraformResourceHandlerTest.java
plugins/scs/pom.xml
plugins/scs/src/test/java/org/eclipse/xpanse/plugins/scs/ScsTerraformResourceHandlerTest.java
pom.xml
runtime/pom.xml
runtime/src/test/java/org/eclipse/xpanse/runtime/AuthorizationApiTest.java

refactor dependencies

---

modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/handler/ServiceMetricsExceptionHandler.java
modules/api/src/test/java/org/eclipse/xpanse/api/exceptions/handler/ServiceMetricsExceptionHandlerTest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/monitor/exceptions/MetricsDataNotYetAvailableException.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/response/ResultType.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/monitor/exceptions/MetricsDataNotYetAvailableExceptionTest.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/utils/FlexibleEngineMetricsService.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/monitor/utils/HuaweiCloudMetricsService.java

fix monitor for HuaweiCloud and FlexibleEngine

---

modules/api/src/main/java/org/eclipse/xpanse/api/AdminServicesApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/config/TerraformBootApiClientConfig.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/system/enums/BackendSystemType.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/system/enums/BackendSystemTypeTest.java
runtime/src/main/resources/application-terraform-boot.properties
runtime/src/main/resources/application.properties
runtime/src/test/java/org/eclipse/xpanse/runtime/AdminServicesApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/AdminServicesApiWithZitadelAndH2DbTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/AdminServicesApiWithZitadelAndMariaDbTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/AuthorizationApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/CredentialManageApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceCatalogApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceMetricsApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceTemplateApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/database/mariadb/AbstractMariaDbIntegrationTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/modules/credential/CredentialOpenApiGeneratorTest.java

add terraformBoot healthCheck to xpanse healthCheck background

---

modules/api/src/main/java/org/eclipse/xpanse/api/ServiceCatalogApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/ServiceTemplateApi.java
modules/api/src/test/java/org/eclipse/xpanse/api/exceptions/handler/CommonExceptionHandlerTest.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicetemplate/DatabaseServiceTemplateStorage.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/query/ServiceTemplateQueryModel.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/query/ServiceTemplateQueryModelTest.java
modules/monitor/src/main/java/org/eclipse/xpanse/modules/monitor/ServiceMetricsAdapter.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java
modules/servicetemplate/src/test/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManageTest.java

fixed https://github.com/eclipse-xpanse/xpanse/issues/791

Isv-User manage service_templates valid namespace

---

plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/utils/FlexibleEngineMetricsService.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/monitor/utils/HuaweiCloudMetricsService.java

Update metrics cache to avoid returning null values

---

modules/api/src/main/java/org/eclipse/xpanse/api/WebhookApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/config/TerraformBootApiClientConfig.java
modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/handler/DeploymentExceptionHandler.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformBootDeployment.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeployment.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/config/TerraformBootConfig.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/config/TerraformLocalConfig.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/api/TerraformApi.java
modules/deployment/src/main/resources/terraformbootApi.json
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/DeployServiceTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeploymentTest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/response/ResultType.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/deploy/exceptions/TerraformBootRequestFailedException.java
modules/security/src/main/java/org/eclipse/xpanse/modules/security/zitadel/config/ZitadelWebSecurityConfig.java
modules/servicetemplate/src/test/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManageTest.java
runtime/src/main/resources/application-terraform-boot.properties
runtime/src/main/resources/application.properties
runtime/src/test/java/org/eclipse/xpanse/runtime/AdminServicesApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/AdminServicesApiWithZitadelAndH2DbTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/AdminServicesApiWithZitadelAndMariaDbTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/AuthorizationApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/CredentialManageApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceCatalogApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceMetricsApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceTemplateApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/database/mariadb/AbstractMariaDbIntegrationTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/modules/credential/CredentialOpenApiGeneratorTest.java

Fixed #758
Fixed #759
Fixed #760

implement terraform deployer using terraform-boot API

---

modules/api/src/main/java/org/eclipse/xpanse/api/AdminServicesApi.java
runtime/src/test/java/org/eclipse/xpanse/runtime/AdminServicesApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/AdminServicesApiWithZitadelAndH2DbTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/AdminServicesApiWithZitadelAndMariaDbTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/AuthorizationApiTest.java

fixed https://github.com/eclipse-xpanse/xpanse/issues/830
related https://github.com/eclipse-xpanse/xpanse-ui/pull/186

Add API to query Csp list

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformBootDeployment.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/config/TerraformBootConfig.java

remove port hard coding in the webhook url

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformBootDeployment.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/849

remove redundant try-catch block

---

README.md
modules/deployment/pom.xml

rename maven property name for generator terraform-boot client

---

modules/api/src/main/java/org/eclipse/xpanse/api/config/TerraformBootApiClientConfig.java
runtime/src/main/resources/application-terraform-boot.properties

update property name terraform-boot.endpoint

---

modules/api/src/main/java/org/eclipse/xpanse/api/AdminServicesApi.java
runtime/src/test/java/org/eclipse/xpanse/runtime/AdminServicesApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/AdminServicesApiWithZitadelAndH2DbTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/AdminServicesApiWithZitadelAndMariaDbTest.java

Enable terraform-boot backed in health conditionally

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformBootDeployment.java

credential vars not sent to terraform-boot

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformBootDeployment.java

webhook - terraform output and deployed resources info not parsed

---

modules/security/src/main/java/org/eclipse/xpanse/modules/security/zitadel/ZitadelIdentityProviderService.java
modules/security/src/main/java/org/eclipse/xpanse/modules/security/zitadel/config/ZitadelWebSecurityConfig.java
runtime/src/main/resources/application-zitadel-testbed.properties
runtime/src/main/resources/application-zitadel.properties
runtime/src/test/java/org/eclipse/xpanse/runtime/AdminServicesApiWithZitadelAndH2DbTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/AdminServicesApiWithZitadelAndMariaDbTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/AuthorizationApiTest.java

change all authorization properties to dot separated

---

modules/security/pom.xml
plugins/flexibleengine/pom.xml
plugins/huaweicloud/pom.xml
plugins/openstack/pom.xml
pom.xml
runtime/pom.xml

fixes https://github.com/eclipse-xpanse/xpanse/issues/876

update the wiremock group id

---

modules/database/src/main/java/org/eclipse/xpanse/modules/database/common/CreateModifiedTime.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/utils/AuditDateTimeProvider.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/common/CreateModifiedTimeTest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/view/ServiceVo.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/view/ServiceTemplateVo.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/view/UserAvailableServiceVo.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/view/ServiceVoTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/view/ServiceTemplateVoTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/view/UserAvailableServiceVoTest.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/utils/ServiceTemplateOpenApiGenerator.java
runtime/src/main/java/org/eclipse/xpanse/runtime/XpanseApplication.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceCatalogApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceTemplateApiTest.java

use correct timestamp format

---

modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceCatalogApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceTemplateApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/database/mariadb/RegistrationWithMariaDbTest.java

fixed [[Registered service template could not be managed by owner](https://github.com/eclipse-xpanse/xpanse/issues/890)](https://github.com/eclipse-xpanse/xpanse/issues/890)

Fix registered service template could not be managed by owner

---

modules/common/pom.xml
pom.xml
runtime/pom.xml
runtime/src/test/java/org/eclipse/xpanse/runtime/ArchitectureTests.java

add archunit tests

---

modules/api/src/main/java/org/eclipse/xpanse/api/config/ResponseValidator.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/common/exceptions/ResponseInvalidException.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/credential/AbstractCredentialInfo.java
modules/security/src/main/java/org/eclipse/xpanse/modules/security/IdentityProviderManager.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/907

add validation to all controller methods

---

modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/utils/ServiceVariablesJsonSchemaGenerator.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/utils/JsonObjectSchema.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/utils/JsonObjectSchemaTest.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/909

validate only variables which are provided by end user

---

.github/workflows/release.yml
jreleaser.yml
modules/api/pom.xml
modules/common/pom.xml
modules/credential/pom.xml
modules/database/pom.xml
modules/deployment/pom.xml
modules/logging/pom.xml
modules/models/pom.xml
modules/monitor/pom.xml
modules/orchestrator/pom.xml
modules/pom.xml
modules/security/pom.xml
modules/servicetemplate/pom.xml
plugins/flexibleengine/pom.xml
plugins/huaweicloud/pom.xml
plugins/openstack/pom.xml
plugins/pom.xml
plugins/scs/pom.xml
pom.xml
runtime/pom.xml

upload runtime jar as release asset

---

.github/workflows/release.yml

update step name

---

jreleaser.yml

related to https://github.com/eclipse-xpanse/xpanse/issues/935

remove merge commits from change log

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/AdminServicesApi.java
modules/database/pom.xml
modules/models/src/main/java/org/eclipse/xpanse/modules/models/system/enums/DatabaseType.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/system/enums/DatabaseTypeTest.java
pom.xml
runtime/pom.xml
runtime/src/main/resources/application-mariadb.properties
runtime/src/main/resources/application-mysql.properties
runtime/src/test/java/org/eclipse/xpanse/runtime/AdminServicesApiWithZitadelAndMysqlTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/database/mysql/AbstractMysqlIntegrationTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/database/mysql/DeploymentWithMysqlTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/database/mysql/RegistrationWithMysqlTest.java

switch default database from mariadb to mysql

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceCatalogApi.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/FlavorBasic.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/view/UserOrderableServiceVo.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/FlavorBasicTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/FlavorTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/view/UserOrderableServiceVoTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceCatalogApiTest.java

fixed #951 
related https://github.com/eclipse-xpanse/xpanse-ui/pull/230

Refactor Flavor data model

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/release-docker-only.yml
.github/workflows/release.yml
modules/workflow/pom.xml
pom.xml

fixes https://github.com/eclipse-xpanse/xpanse/issues/966

update java version

---

modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DatabaseDeployServiceStorage.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DeployServiceStorage.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/service/DatabaseDeployServiceStorageTest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/workflow/src/main/java/org/eclipse/xpanse/modules/workflow/handle/migrate/MigrateDeployProcess.java
modules/workflow/src/main/java/org/eclipse/xpanse/modules/workflow/handle/migrate/MigrateDestroyProcess.java

extend migrate service for terraform-boot

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceDeployerApi.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/971

update service status before accepting destroy request.

---

modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/cache/CredentialCacheKey.java

Add option in UI to manage ISV credentials

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceDeployerApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/WorkFlowApi.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/DeployServiceTest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/policy/PolicyCreateRequest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/policy/PolicyUpdateRequest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/policy/PolicyVo.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/view/ServiceVo.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/policy/PolicyCreateRequestTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/policy/PolicyUpdateRequestTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/policy/PolicyVoTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/view/ServiceVoTest.java
modules/policy/src/test/java/org/eclipse/xpanse/modules/policy/policyman/PolicyManagerTest.java
modules/workflow/src/main/java/org/eclipse/xpanse/modules/workflow/handle/migrate/MigrateDestroyProcess.java
runtime/src/test/java/org/eclipse/xpanse/runtime/PolicyManageApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java

Remove unused field userId

---

modules/models/src/main/java/org/eclipse/xpanse/modules/models/policy/PolicyCreateRequest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/policy/PolicyCreateRequestTest.java
modules/policy/src/main/java/org/eclipse/xpanse/modules/policy/policyman/PolicyManager.java

fixes eclipse-xpanse/xpanse#1004

add enabled to policyCreateRequestBody.

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformBootDeployment.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeployment.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironments.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformBootDeploymentTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeploymentTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironmentsTest.java

Update service deployer to support both end user and ISV credentials

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceCatalogApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceTemplateApi.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicetemplate/DatabaseServiceTemplateStorage.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/query/ServiceTemplateQueryModel.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/query/ServiceTemplateQueryModelTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/database/mysql/RegistrationWithMysqlTest.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/1010

allow same service to be hosted in both ways

---

modules/models/src/main/java/org/eclipse/xpanse/modules/models/policy/PolicyCreateRequest.java

related to  https://github.com/eclipse-xpanse/xpanse/issues/1004

make enabled mandatory.

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/IsvServiceDeployApi.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DeployServiceEntity.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/service/DeployServiceEntityTest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/deployment/DeployTask.java
modules/orchestrator/src/test/java/org/eclipse/xpanse/modules/orchestrator/deployment/DeployTaskTest.java
modules/security/src/main/java/org/eclipse/xpanse/modules/security/IdentityProviderManager.java

Provide listDeployedServices service for ISV

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/CredentialsConfigApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/UserCloudCredentialsApi.java
modules/api/src/test/java/org/eclipse/xpanse/api/exceptions/handler/CredentialManageExceptionHandlerTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/UserCloudCredentialsApiTest.java

update request URI for end user credentials management

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceDeployerApi.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java
modules/servicetemplate/src/test/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManageTest.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/1018

block service hosting type update in template

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/PolicyManageApi.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DatabaseDeployServiceStorage.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DeployServiceStorage.java
modules/deployment/pom.xml
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformBootDeployment.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeployment.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformExecutor.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/DeployServiceTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformBootDeploymentTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeploymentTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironmentsTest.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/deployment/Deployment.java
modules/policy/src/main/java/org/eclipse/xpanse/modules/policy/policyman/PolicyManager.java
modules/policy/src/test/java/org/eclipse/xpanse/modules/policy/policyman/PolicyManagerTest.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/956

validate deployment plan with enabled policies

---

modules/common/src/main/java/org/eclipse/xpanse/common/openapi/OpenApiGeneratorJarManage.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/servicetemplate/ServiceTemplateEntityTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformBootDeploymentTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeploymentTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironmentsTest.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/utils/IconProcessorUtil.java
modules/servicetemplate/src/test/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManageTest.java
plugins/flexibleengine/src/test/java/org/eclipse/xpanse/plugins/flexibleengine/FlexibleEngineTerraformResourceHandlerTest.java
plugins/huaweicloud/src/test/java/org/eclipse/xpanse/plugins/huaweicloud/HuaweiTerraformResourceHandlerTest.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/monitor/keystone/KeystoneManager.java
plugins/openstack/src/test/java/org/eclipse/xpanse/plugins/openstack/OpenstackTerraformResourceHandlerTest.java
plugins/scs/src/test/java/org/eclipse/xpanse/plugins/scs/ScsTerraformResourceHandlerTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceCatalogApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceTemplateApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/database/mysql/DeploymentWithMysqlTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/database/mysql/RegistrationWithMysqlTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/modules/common/OpenApiGeneratorJarManageTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/modules/servicetemplate/utils/ServiceTemplateOpenApiGeneratorTest.java

replace use of deprecated "new URL" method

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/view/ServiceVo.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/view/ServiceVoTest.java

return service hosting info

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/IsvServiceDeployApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/handler/DeploymentExceptionHandler.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/utils/EntityTransUtils.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/DeployServiceTest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/response/ResultType.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/deploy/exceptions/ServiceDetailsNotAccessible.java

Create new ISV user service -> getServiceDetailsByIdForIsv

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceDeployerApi.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/utils/EntityTransUtils.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/view/VendorHostedServiceDetailsVo.java

Create new end user service -> getVendorHostedServiceDetailsById

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceDeployerApi.java
modules/api/src/test/java/org/eclipse/xpanse/api/exceptions/handler/DeploymentExceptionHandlerTest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/DeployServiceTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/database/mysql/DeploymentWithMysqlTest.java

update getServiceDetailsById to return only self-hosted services

---

modules/database/src/main/java/org/eclipse/xpanse/modules/database/policy/PolicyEntity.java

fix storing large policy fails

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/DeployServiceTest.java

all destroy requests failing

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java

TerraformBoot callback APIs of Xpanse retruns unexpected authentication exception.

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformBootDeployment.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformBootDeploymentTest.java

incorrect response returned when terraform-boot is not reachable

---

modules/security/src/main/java/org/eclipse/xpanse/modules/security/IdentityProviderManager.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java
modules/servicetemplate/src/test/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManageTest.java

Create simple dashboard for ISV user

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/IsvServiceDeployApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/PolicyManageApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceDeployerApi.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/utils/EntityTransUtils.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/DeployServiceTest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/policy/Policy.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/view/DeployedService.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/view/DeployedServiceDetails.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/view/VendorHostedDeployedServiceDetails.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/policy/PolicyVoTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/view/DeployedServiceDetailsTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/view/ServiceVoTest.java
modules/policy/src/main/java/org/eclipse/xpanse/modules/policy/policyman/PolicyManager.java
modules/policy/src/test/java/org/eclipse/xpanse/modules/policy/policyman/PolicyManagerTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/PolicyManageApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/WebhookApiTest.java

Remove 'Vo' from model names

---

plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/models/FlexibleEngineTerraformResourceProperties.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/models/HuaweiCloudTerraformResourceProperties.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/enums/OpenstackTerraformResourceProperties.java
plugins/scs/src/main/java/org/eclipse/xpanse/plugins/scs/enums/ScsTerraformResourceProperties.java

fix shown property of the resource security group rule is error

---

modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DatabaseDeployServiceStorage.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DeployServiceStorage.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/service/DatabaseDeployServiceStorageTest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/workflow/src/main/java/org/eclipse/xpanse/modules/workflow/handle/migrate/MigrateDeployProcess.java
modules/workflow/src/main/java/org/eclipse/xpanse/modules/workflow/handle/migrate/MigrateDestroyProcess.java

Fix Migration service workflow blocked in the service deployment task

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/IsvServiceDeployApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceDeployerApi.java
modules/api/src/test/java/org/eclipse/xpanse/api/exceptions/handler/DeploymentExceptionHandlerTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/AuthorizationApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/WebhookApiTest.java

fix URIs for service details related services

---

modules/security/pom.xml
plugins/flexibleengine/pom.xml
plugins/huaweicloud/pom.xml
plugins/openstack/pom.xml
pom.xml
runtime/pom.xml
runtime/src/test/java/org/eclipse/xpanse/runtime/WebhookApiTest.java

related to https://github.com/eclipse-xpanse/xpanse/issues/1071

upgrade spring-boot version

---

modules/observability/pom.xml
modules/observability/src/main/java/org/eclipse/xpanse/modules/observability/OpenTelemetryConfiguration.java
modules/pom.xml
pom.xml
runtime/pom.xml
runtime/src/main/resources/application-opentelemetry.properties
runtime/src/main/resources/application.properties
runtime/src/main/resources/logback.xml

fixes https://github.com/eclipse-xpanse/xpanse/issues/1070

add opentelemetry exporter

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
runtime/src/test/java/org/eclipse/xpanse/runtime/database/mysql/DeploymentWithMysqlTest.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/1084

perform rollback only when resources are provisioned

---

jreleaser.yml

fixes  https://github.com/eclipse-xpanse/xpanse/issues/1087

remove bot commits from change log

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/deploy/enums/ServiceDeploymentState.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/deploy/enums/ServiceDeploymentStateTest.java

Update deployment state when rollback fails or successes

---

modules/api/pom.xml
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/AdminServicesApi.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/system/enums/BackendSystemType.java
modules/observability/pom.xml
modules/observability/src/main/java/org/eclipse/xpanse/modules/observability/OpenTelemetryCollectorHealthCheck.java
modules/observability/src/main/java/org/eclipse/xpanse/modules/observability/model/CollectorStatus.java
modules/observability/src/main/java/org/eclipse/xpanse/modules/observability/model/OpenTelemetryHealthCheckResponse.java
runtime/src/main/resources/application-opentelemetry.properties

fixes https://github.com/eclipse-xpanse/xpanse/issues/1082

add otel collector to healthcheck

---

jreleaser.yml

fixes https://github.com/eclipse-xpanse/xpanse/issues/1102

update contributor information

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformBootDeployment.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/1107

handle RestClientException from terraform-boot API for validate request

---

modules/database/src/main/java/org/eclipse/xpanse/modules/database/EnumColumnAllowedValuesUpdater.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DatabaseDeployServiceStorage.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/deployment/DeployTask.java
modules/orchestrator/src/test/java/org/eclipse/xpanse/modules/orchestrator/deployment/DeployTaskTest.java
modules/policy/src/main/java/org/eclipse/xpanse/modules/policy/policyman/PolicyManager.java
modules/policy/src/test/java/org/eclipse/xpanse/modules/policy/policyman/PolicyManagerTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/1121
service policies valid failed:
user policies valid failed:

validate service policies before deployment

---

.github/workflows/license-checks.yml
DEPENDENCIES
README.md
pom.xml

related to https://github.com/eclipse-xpanse/xpanse/issues/1148

integrate eclipse dash-licenses tool

---

modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DeployServiceEntity.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/service/DeployServiceEntityTest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/view/DeployedService.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/view/DeployedServiceTest.java

add service started and service stopped time

---

modules/workflow/pom.xml
modules/workflow/src/main/java/org/eclipse/xpanse/modules/workflow/config/ActivitiConfig.java
modules/workflow/src/main/java/org/eclipse/xpanse/modules/workflow/utils/WorkflowProcessUtils.java
pom.xml
runtime/src/main/java/org/eclipse/xpanse/runtime/XpanseApplication.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/1172

dependencies - upgrade to latest activiti version

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeployment.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/1181

fix - handle when tfstate file is not found

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java

generate terraform plan only if there is any policy to be validated

---

plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/OpenstackOrchestratorPlugin.java
plugins/openstack/src/test/java/org/eclipse/xpanse/plugins/openstack/OpenstackOrchestratorPluginTest.java
samples/openstack-Kafka.yml

fixes https://github.com/eclipse-xpanse/xpanse/issues/1206

fix - remove JVM level environment var OS_AUTH_URL

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceDeployerApi.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeployment.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeploymentTest.java
modules/servicetemplate/src/test/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManageTest.java
modules/workflow/src/main/java/org/eclipse/xpanse/modules/workflow/handle/migrate/MigrateDeployProcess.java
modules/workflow/src/main/java/org/eclipse/xpanse/modules/workflow/handle/migrate/MigrateDestroyProcess.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java

Fixed #1078
related to eclipse-xpanse/terraform-boot#72

remove async threads when terraform-boot is activated

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/OpenstackOrchestratorPlugin.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/common/constants/OpenstackEnvironmentConstants.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/common/keystone/CustomEndPointResolver.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/common/keystone/KeystoneManager.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/manage/ServersManager.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/monitor/MetricsManager.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/monitor/gnocchi/api/AggregationService.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/monitor/gnocchi/api/MeasuresService.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/monitor/gnocchi/utils/GnocchiToXpanseModelConverter.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/monitor/gnocchi/utils/MetricsQueryBuilder.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/resourcehandler/OpenstackTerraformResourceHandler.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/resourcehandler/OpenstackTerraformResourceProperties.java
plugins/openstack/src/test/java/org/eclipse/xpanse/plugins/openstack/OpenstackOrchestratorPluginTest.java
plugins/openstack/src/test/java/org/eclipse/xpanse/plugins/openstack/common/keystone/CustomEndPointResolverTest.java
plugins/openstack/src/test/java/org/eclipse/xpanse/plugins/openstack/monitor/OpenstackMonitoringIntegrationTest.java
plugins/openstack/src/test/java/org/eclipse/xpanse/plugins/openstack/resourehandler/OpenstackTerraformResourceHandlerTest.java
plugins/openstack/src/test/java/org/eclipse/xpanse/plugins/openstack/resourehandler/OpenstackTerraformResourcePropertiesTest.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/1161

implement server start-stop methods in openstack plugin

---

modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/handler/DeploymentExceptionHandler.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/response/ResultType.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/deploy/exceptions/ActivitiTaskNotFoundException.java
modules/workflow/src/main/java/org/eclipse/xpanse/modules/workflow/utils/WorkflowProcessUtils.java

workflowApi - PUT requests return http 500 if ID is unknown

---

.github/workflows/release-docker-only.yml
.github/workflows/release.yml
.github/workflows/upload-swaggerhub-only.yml
pom.xml

related to https://github.com/eclipse-xpanse/xpanse/issues/1215

fix job config

---

DEPENDENCIES
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformBootDeployment.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeployment.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironments.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformBootDeploymentTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeploymentTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironmentsTest.java
modules/monitor/src/main/java/org/eclipse/xpanse/modules/monitor/ServiceMetricsAdapter.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/manage/ServiceManagerRequest.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/monitor/MetricsRequest.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/monitor/ResourceMetricsRequest.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/monitor/ServiceMetricsRequest.java
modules/orchestrator/src/test/java/org/eclipse/xpanse/modules/orchestrator/monitor/MetricsRequestTest.java
modules/orchestrator/src/test/java/org/eclipse/xpanse/modules/orchestrator/monitor/ResourceMetricsRequestTest.java
modules/orchestrator/src/test/java/org/eclipse/xpanse/modules/orchestrator/monitor/ServiceMetricsRequestTest.java
plugins/flexibleengine/src/test/java/org/eclipse/xpanse/plugins/flexibleengine/FlexibleEngineOrchestratorPluginTest.java
plugins/flexibleengine/src/test/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/FlexibleEngineMonitorIntegrationTest.java
plugins/huaweicloud/src/test/java/org/eclipse/xpanse/plugins/huaweicloud/HuaweiCloudOrchestratorPluginTest.java
plugins/huaweicloud/src/test/java/org/eclipse/xpanse/plugins/huaweicloud/monitor/HuaweiCloudMonitorIntegrationTest.java
plugins/openstack/pom.xml
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/OpenstackOrchestratorPlugin.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/common/keystone/KeystoneManager.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/manage/ServersManager.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/monitor/MetricsManager.java
plugins/openstack/src/test/java/org/eclipse/xpanse/plugins/openstack/OpenstackOrchestratorPluginTest.java
plugins/openstack/src/test/java/org/eclipse/xpanse/plugins/openstack/monitor/OpenstackMonitoringIntegrationTest.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/1221
@iskey the changes might look big. But just the methods are just split. No big functional changees.

use deploy variables in metrics adapter

---

plugins/scs/pom.xml
plugins/scs/src/main/java/org/eclipse/xpanse/plugins/scs/ScsOrchestratorPlugin.java
plugins/scs/src/main/java/org/eclipse/xpanse/plugins/scs/common/constants/ScsEnvironmentConstants.java
plugins/scs/src/main/java/org/eclipse/xpanse/plugins/scs/common/keystone/ScsKeystoneManager.java
plugins/scs/src/main/java/org/eclipse/xpanse/plugins/scs/manage/ScsServersManager.java
plugins/scs/src/test/java/org/eclipse/xpanse/plugins/scs/ScsOrchestratorPluginTest.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/1209

implement VM start-stop for SCS plugin

---

modules/workflow/pom.xml
modules/workflow/src/main/java/org/eclipse/xpanse/modules/workflow/config/ActivitiConfig.java
pom.xml

generate activiti processInstanceId as UUID and use this as Migration  Request ID

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/IsvServiceDeployApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceDeployerApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceStateManageApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/WebhookApi.java
modules/api/src/test/java/org/eclipse/xpanse/api/exceptions/handler/DeploymentExceptionHandlerTest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployServiceEntityHandler.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployServiceEntityToDeployTaskConverter.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployerKindManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeploymentResultCallbackManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/PolicyValidator.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ResourceHandlerManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/SensitiveDataHandler.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceDetailsViewManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceStateManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeployment.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeploymentTest.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/deployment/DeployTask.java
modules/orchestrator/src/test/java/org/eclipse/xpanse/modules/orchestrator/deployment/DeployTaskTest.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java
modules/servicetemplate/src/test/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManageTest.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/OpenstackOrchestratorPlugin.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/1251

split DeployService class into multiple classes

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceTemplateApi.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicetemplate/ServiceTemplateEntity.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/servicetemplate/ServiceTemplateEntityTest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/Ocl.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/ServiceProviderContactDetails.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/view/ServiceTemplateDetailVo.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/OclTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/view/ServiceTemplateDetailVoTest.java
modules/orchestrator/src/test/java/org/eclipse/xpanse/modules/orchestrator/deployment/DeployTaskTest.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java
runtime/src/test/resources/ocl_test.yaml
runtime/src/test/resources/ocl_testOpenApi.yaml
runtime/src/test/resources/ocl_test_dummy.yaml
samples/flexibleEngine-K8S.yml
samples/flexibleEngine-Kafka.yml
samples/huawei-K8S.yml
samples/huawei-Kafka-terraform_module.yml
samples/huawei-Kafka.yml
samples/openstack-Kafka.yml
samples/scs-Kafka.yml

Extend OCL to have service provider details.

---

modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicepolicy/ServicePolicyEntity.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/servicepolicy/ServicePolicyEntityTest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/PolicyValidator.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/policy/servicepolicy/ServicePolicy.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/policy/servicepolicy/ServicePolicyCreateRequest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/policy/servicepolicy/ServicePolicyCreateRequestTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/policy/servicepolicy/ServicePolicyTest.java
modules/policy/src/main/java/org/eclipse/xpanse/modules/policy/ServicePolicyManager.java
samples/flexibleEngine-K8S.json
samples/flexibleEngine-Kafka.json
samples/huawei-K8S.json
samples/huawei-Kafka.json

implement flavor specific service policies

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceDeployerApi.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java

threads in purge request

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceStateManager.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/manage/HuaweiCloudVmStateManager.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/1278

fix - condition for huaweicloud async request retry

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceMigrationApi.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/utils/EntityTransUtils.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/migration/MigrationService.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/workflow/migrate/view/ServiceMigrationDetails.java

New API method to get migration order details

---

modules/models/src/main/java/org/eclipse/xpanse/modules/models/policy/servicepolicy/ServicePolicyUpdateRequest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/policy/servicepolicy/ServicePolicyUpdateRequestTest.java
modules/policy/src/main/java/org/eclipse/xpanse/modules/policy/ServicePolicyManager.java
modules/policy/src/test/java/org/eclipse/xpanse/modules/policy/policyman/ServicePolicyManagerTest.java

Update service policy support flavor name

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java

migrate workflow does not set "DESTROYING" status

---

modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicepolicy/ServicePolicyEntity.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/servicepolicy/ServicePolicyEntityTest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/PolicyValidator.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/policy/servicepolicy/ServicePolicy.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/policy/servicepolicy/ServicePolicyCreateRequest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/policy/servicepolicy/ServicePolicyUpdateRequest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/policy/servicepolicy/ServicePolicyCreateRequestTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/policy/servicepolicy/ServicePolicyTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/policy/servicepolicy/ServicePolicyUpdateRequestTest.java
modules/policy/src/main/java/org/eclipse/xpanse/modules/policy/ServicePolicyManager.java
modules/policy/src/test/java/org/eclipse/xpanse/modules/policy/policyman/ServicePolicyManagerTest.java

support service policies to be linked to multiple service flavors

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/migration/steps/DeployFailedManualHandlerListener.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/migration/steps/DestroyFailedManualHandlerListener.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/migration/steps/ExportData.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/migration/steps/ImportData.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/migration/steps/ProcessDeploymentResult.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/migration/steps/ProcessDestroyResult.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/migration/steps/StartDeploy.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/migration/steps/StartDestroy.java
modules/workflow/src/main/java/org/eclipse/xpanse/modules/workflow/config/ActivitiConfig.java
modules/workflow/src/main/java/org/eclipse/xpanse/modules/workflow/utils/WorkflowUtils.java
modules/workflow/src/main/resources/processes/migrate.bpmn20.xml

fixes https://github.com/eclipse-xpanse/xpanse/issues/1285

use beans directly in activiti workflows

---

.github/dependabot.yml
DEPENDENCIES
modules/credential/pom.xml
modules/credential/src/test/java/org/eclipse/xpanse/modules/credential/CredentialCacheTests.java
modules/servicetemplate/pom.xml
pom.xml
runtime/pom.xml

dependencies: remove awaitility which is now implicitly provided by spring-boot-test

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceCatalogApi.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/view/UserOrderableServiceVo.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/view/UserOrderableServiceVoTest.java

add serviceProviderContactDetails for deploy service.

---

modules/api/src/main/java/org/eclipse/xpanse/api/config/TaskStatusEnumConverter.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/WorkFlowApi.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/workflow/TaskStatus.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/workflow/WorkFlowTask.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/workflow/WorkFlowTaskTest.java
modules/workflow/src/main/java/org/eclipse/xpanse/modules/workflow/utils/WorkflowUtils.java

add new component to show workflow tasks assigned to user

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceDeployerApi.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceDetailsViewManager.java

details option for vendor hosted services to be optionally enabled

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/OpenTofuDeployment.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/OpenTofuExecutor.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/TerraformBootDeployment.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/TerraformBootScriptValidator.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformlocal/TerraformLocalDeployment.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformlocal/TerraformLocalExecutor.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformBootDeploymentTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformLocalDeploymentTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformlocal/TerraformLocalExecutorTest.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/deployment/Deployer.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/deployment/DeploymentScriptValidationResult.java
modules/orchestrator/src/test/java/org/eclipse/xpanse/modules/orchestrator/deployment/DeploymentScriptValidationResultTest.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java

rename class DeployValidationResult

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceStateManager.java

set "lastStartedAt" and "lastStoppedAt" initial values

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java

update service migrate ui

---

modules/api/src/main/java/org/eclipse/xpanse/api/config/ServiceTemplateEntityConverter.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/CspServiceTemplateApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceCatalogApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceTemplateApi.java
modules/api/src/test/java/org/eclipse/xpanse/api/config/CspEnumConverterTest.java
modules/api/src/test/java/org/eclipse/xpanse/api/exceptions/handler/CommonExceptionHandlerTest.java
modules/api/src/test/java/org/eclipse/xpanse/api/exceptions/handler/RegistrationExceptionHandlerTest.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicetemplate/ServiceTemplateQueryModel.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/servicetemplate/ServiceTemplateQueryModelTest.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java
modules/servicetemplate/src/test/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManageTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/AdminServicesApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/CspServiceTemplateApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceTemplateApiTest.java
runtime/src/test/resources/jwt_admin.json
runtime/src/test/resources/jwt_admin_csp.json
runtime/src/test/resources/jwt_all_roles.json
runtime/src/test/resources/jwt_no_roles.json
runtime/src/test/resources/jwt_user.json
runtime/src/test/resources/jwt_user_unique.json

fixes #1378 
related https://github.com/eclipse-xpanse/xpanse-iam/pull/17

Add interface for querying all registered service templates for the role CSP

---

modules/api/src/main/java/org/eclipse/xpanse/api/config/DeployResourceKindEnumConverter.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ExistingCloudResourcesApi.java
modules/credential/src/test/java/org/eclipse/xpanse/modules/credential/DummyPluginImpl.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironmentsTest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/deploy/enums/DeployResourceKind.java
modules/monitor/src/test/java/org/eclipse/xpanse/modules/monitor/ServiceMetricsAdapterTest.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/deployment/ServiceResourceHandler.java
modules/orchestrator/src/test/java/org/eclipse/xpanse/modules/orchestrator/DummyFlexibleEnginePluginImpl.java
modules/orchestrator/src/test/java/org/eclipse/xpanse/modules/orchestrator/DummyOpenstackPluginImpl.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/FlexibleEngineOrchestratorPlugin.java
plugins/huaweicloud/pom.xml
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/HuaweiCloudOrchestratorPlugin.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/common/HuaweiCloudClient.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/manage/HuaweiCloudResourceManager.java
plugins/huaweicloud/src/test/java/org/eclipse/xpanse/plugins/huaweicloud/monitor/HuaweiCloudMonitorIntegrationTest.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/OpenstackOrchestratorPlugin.java
plugins/scs/src/main/java/org/eclipse/xpanse/plugins/scs/ScsOrchestratorPlugin.java

create new API method getExistingResourcesOfType

---

modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DeployServiceEntity.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/utils/EntityTransUtils.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/service/DeployServiceEntityTest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployServiceEntityToDeployTaskConverter.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/SensitiveDataHandler.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceDetailsViewManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/callbacks/OpenTofuDeploymentResultCallbackManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/callbacks/TerraformDeploymentResultCallbackManager.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/opentofulocal/OpenTofuLocalDeploymentTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/tofumaker/TofuMakerDeploymentTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/TerraformBootDeploymentTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformlocal/TerraformLocalDeploymentTest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/deploy/DeployRequestBase.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/view/DeployedService.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/deploy/DeployRequestTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/view/DeployedServiceTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/workflow/migrate/MigrateRequestTest.java
modules/policy/src/main/java/org/eclipse/xpanse/modules/policy/ServicePolicyManager.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/common/keystone/KeystoneManager.java
plugins/openstack/src/test/java/org/eclipse/xpanse/plugins/openstack/monitor/OpenstackMonitoringIntegrationTest.java
plugins/scs/src/main/java/org/eclipse/xpanse/plugins/scs/common/keystone/ScsKeystoneManager.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java

Link service template ID and the DeployedService data.

---

modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/deploy/enums/DeployResourceKind.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/AutoFill.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/DeployVariable.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/DeployVariableTest.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/utils/DeployVariableAutoFillValidator.java
samples/develop/huawei-compute-opentofu-dev-autofill.yml
samples/develop/huawei-compute-terraform-dev-autofill.yml
samples/huawei-K8S-autofill.yml
samples/huawei-Kafka-autofill.yml

Extend OCL to provide auto-fill for deploy variables

---

plugins/flexibleengine/pom.xml
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/FlexibleEngineOrchestratorPlugin.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/common/FlexibleEngineClient.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/common/FlexibleEngineConstants.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/manage/FlexibleEngineResourceManager.java
plugins/flexibleengine/src/test/java/org/eclipse/xpanse/plugins/flexibleengine/FlexibleEngineOrchestratorPluginTest.java
plugins/flexibleengine/src/test/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/FlexibleEngineMonitorIntegrationTest.java

implement getResourcesOfType for FlexibleEngine plugin

---

plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/OpenstackOrchestratorPlugin.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/common/keystone/KeystoneManager.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/manage/OpenStackResourceManager.java
plugins/openstack/src/test/java/org/eclipse/xpanse/plugins/openstack/OpenstackOrchestratorPluginTest.java
plugins/openstack/src/test/java/org/eclipse/xpanse/plugins/openstack/monitor/OpenstackMonitoringIntegrationTest.java

implement getResourcesOfType for OpenStack plugin

---

modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/view/ServiceTemplateDetailVo.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/view/ServiceTemplateDetailVoTest.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java
runtime/src/test/java/org/eclipse/xpanse/runtime/CspServiceTemplateApiTest.java

Add field reviewComment in service template view object

---

modules/api/src/main/java/org/eclipse/xpanse/api/config/DeployResourceKindEnumConverter.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/opentofulocal/OpenTofuLocalDeployment.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformlocal/TerraformLocalDeployment.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/manage/FlexibleEngineResourceManager.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/manage/HuaweiCloudResourceManager.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/manage/OpenStackResourceManager.java
plugins/scs/src/main/java/org/eclipse/xpanse/plugins/scs/manage/ScsResourceManager.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/1344

catch all runtime exceptions during deploy and destroy

---

modules/api/src/main/java/org/eclipse/xpanse/api/config/ServiceTemplateEntityConverter.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ExistingCloudResourcesApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceDeployerApi.java
modules/credential/src/test/java/org/eclipse/xpanse/modules/credential/DummyPluginImpl.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironmentsTest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/view/UserOrderableServiceVo.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/view/UserOrderableServiceVoTest.java
modules/monitor/src/test/java/org/eclipse/xpanse/modules/monitor/ServiceMetricsAdapterTest.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/deployment/ServiceResourceHandler.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/FlexibleEngineOrchestratorPlugin.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/manage/FlexibleEngineResourceManager.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/HuaweiCloudOrchestratorPlugin.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/manage/HuaweiCloudResourceManager.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/OpenstackOrchestratorPlugin.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/manage/OpenStackResourceManager.java
plugins/scs/src/main/java/org/eclipse/xpanse/plugins/scs/ScsOrchestratorPlugin.java
plugins/scs/src/main/java/org/eclipse/xpanse/plugins/scs/manage/ScsResourceManager.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceCatalogApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/database/mysql/DeploymentWithMysqlTest.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/1441
related to https://github.com/eclipse-xpanse/xpanse-ui/pull/617
List availability zones with csp `huawei` and region `cn-southwest-2`:
List availability zones with csp `flexibleengine` and region `eu-west-0`:

Add Service to list availability zones with region of csp

---

runtime/src/test/resources/ocl_opentofu_test.yml
runtime/src/test/resources/ocl_terraform_test.yml
runtime/src/test/resources/ocl_terraform_update.yml
samples/develop/flexibleEngine-compute-terraform-dev.yml
samples/develop/huawei-compute-opentofu-dev-autofill.yml
samples/develop/huawei-compute-opentofu-dev.yml
samples/develop/huawei-compute-terraform-dev-autofill.yml
samples/develop/huawei-compute-terraform-dev.yml
samples/develop/openstack-compute-terraform-dev.yml
samples/flexibleEngine-K8S.yml
samples/flexibleEngine-Kafka.yml
samples/huawei-K8S-autofill.yml
samples/huawei-K8S.yml
samples/huawei-Kafka-autofill.yml
samples/huawei-Kafka-terraform_module.yml
samples/huawei-Kafka.yml
samples/openstack-Kafka.yml
samples/plus-server-Kafka.yml
samples/regio-cloud-Kafka.yml

Fixed #1442
related to eclipse-xpanse/xpanse-ui#621

Add AZ to order and migrate form

---

modules/api/src/test/resources/ocl_terraform_test.yml
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/DeployVariable.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/Flavor.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/ModificationImpact.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/DeployVariableTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/FlavorTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/ModificationImpactTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceTemplateApiTest.java
runtime/src/test/resources/ocl_opentofu_test.yml
runtime/src/test/resources/ocl_terraform_test.yml
runtime/src/test/resources/ocl_terraform_update.yml
samples/develop/huawei-compute-opentofu-dev-autofill.yml
samples/develop/huawei-compute-opentofu-dev-git-repo.yml
samples/develop/huawei-compute-opentofu-dev.yml
samples/develop/huawei-compute-terraform-dev-autofill.yml
samples/develop/huawei-compute-terraform-dev-git-repo.yml
samples/develop/huawei-compute-terraform-dev.yml
samples/flexibleEngine-K8S.yml
samples/flexibleEngine-Kafka.yml
samples/huawei-K8S-autofill.yml
samples/huawei-K8S.yml
samples/huawei-Kafka-autofill.yml
samples/huawei-Kafka-terraform_module.yml
samples/huawei-Kafka.yml
samples/openstack-Kafka.yml
samples/plus-server-Kafka.yml
samples/regio-cloud-Kafka.yml

update OCL to support service specification modifications.

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/AuthorizationApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/CredentialsConfigApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/CspServiceTemplateApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ExistingCloudResourcesApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/IsvCloudCredentialsApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceCatalogApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServicePolicyManageApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceStateManageApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceTemplateApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/UserCloudCredentialsApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/UserPolicyManageApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/WorkFlowApi.java
modules/security/src/main/java/org/eclipse/xpanse/modules/security/OpenApiOauth2Config.java

Fixed #1484
related to eclipse-xpanse/xpanse-ui/pull/659

An error occurs when importing Xpanse OpenAPI files into HuaweiCloud's APIG service.

---

samples/develop/flexibleEngine-compute-terraform-dev.yml
samples/develop/huawei-compute-opentofu-dev-autofill.yml
samples/develop/huawei-compute-opentofu-dev-git-repo.yml
samples/develop/huawei-compute-opentofu-dev.yml
samples/develop/huawei-compute-terraform-dev-autofill.yml
samples/develop/huawei-compute-terraform-dev-git-repo.yml
samples/develop/huawei-compute-terraform-dev.yml
samples/develop/openstack-compute-terraform-dev.yml
samples/flexibleEngine-K8S.yml
samples/flexibleEngine-Kafka.yml
samples/huawei-K8S-autofill.yml
samples/huawei-K8S.yml
samples/huawei-Kafka-autofill.yml
samples/huawei-Kafka-terraform_module.yml
samples/huawei-Kafka.yml
samples/huawei-mysql.yml
samples/plus-server-Kafka.yml

fix error samples

---

modules/workflow/src/main/resources/processes/migrate.bpmn20.xml

fixes #1510 
Change gateways  to `exclusiveGateway`

update error gateway in migrate workflow template

---

plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/common/FlexibleEngineClient.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/manage/FlexibleEngineResourceManager.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/manage/HuaweiCloudResourceManager.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/manage/OpenstackResourceManager.java
plugins/scs/src/main/java/org/eclipse/xpanse/plugins/scs/manage/ScsResourceManager.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ExistingCloudResourcesApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/1520

Return empty list even if the SDK method throw exception

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java

update service state for modify.

---

pom.xml
runtime/pom.xml

fixes https://github.com/eclipse-xpanse/xpanse/issues/1551

fix version in API uploaded to swaggerhub

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java

fixes #1563 
Service data before modification:
Modify service:
Service data after modification failed:
Service data after modification success:

Store modify info into DB

---

modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/modify/ModifyRequest.java

update customerServiceName for ModifyRequest.

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceDeployerApi.java

update lock log.

---

modules/api/src/main/java/org/eclipse/xpanse/api/config/ServiceTemplateEntityConverter.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceMigrationApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServicePolicyManageApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/handler/DeploymentExceptionHandler.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/migration/MigrationService.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/policy/servicepolicy/ServicePolicyUpdateRequest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/response/ResultType.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/deploy/DeployRequestBase.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/deploy/exceptions/EulaNotAccepted.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/Ocl.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/utils/OptionalToStringSerializer.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/view/ServiceTemplateDetailVo.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/view/UserOrderableServiceVo.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/policy/servicepolicy/ServicePolicyUpdateRequestTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/deploy/DeployRequestTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/OclTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/view/ServiceTemplateDetailVoTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/view/UserOrderableServiceVoTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/workflow/migrate/MigrateRequestTest.java
modules/policy/src/main/java/org/eclipse/xpanse/modules/policy/ServicePolicyManager.java
modules/policy/src/test/java/org/eclipse/xpanse/modules/policy/policyman/ServicePolicyManagerTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceCatalogApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServicePolicyManageApiTest.java
samples/develop/huawei-compute-opentofu-dev-eula.yml
samples/develop/huawei-compute-terraform-dev-eula.yml
samples/huawei-K8S-eula.yml
samples/huawei-Kafka-eula.yml

Fixed #1540  and #1541
related to eclipse-xpanse/xpanse-ui#730

add eula status to deploymentRequest and service templates

---

modules/api/src/test/resources/ocl_terraform_test.yml
modules/database/src/test/resources/ocl_terraform_test.yml
modules/deployment/src/test/resources/ocl_terraform_from_git_test.yml
modules/deployment/src/test/resources/ocl_terraform_test.yml
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/ServiceFlavor.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/ServiceFlavorTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/ServiceFlavorWithPriceTest.java
modules/models/src/test/resources/ocl_terraform_test.yml
modules/servicetemplate/src/test/resources/ocl_terraform_test.yml
runtime/src/test/resources/ocl_terraform_from_git_test.yml
runtime/src/test/resources/ocl_terraform_test.yml
samples/develop/flexibleEngine-compute-terraform-dev.yml
samples/develop/huawei-compute-opentofu-dev-autofill.yml
samples/develop/huawei-compute-opentofu-dev-git-repo.yml
samples/develop/huawei-compute-opentofu-dev.yml
samples/develop/huawei-compute-terraform-dev-autofill.yml
samples/develop/huawei-compute-terraform-dev-git-repo.yml
samples/develop/huawei-compute-terraform-dev.yml
samples/develop/openstack-compute-terraform-dev.yml
samples/flexibleEngine-K8S.yml
samples/flexibleEngine-Kafka.yml
samples/huawei-K8S-autofill.yml
samples/huawei-K8S.yml
samples/huawei-Kafka-autofill.yml
samples/huawei-Kafka-terraform_module.yml
samples/huawei-Kafka.yml
samples/huawei-mysql.yml
samples/openstack-Kafka.yml
samples/plus-server-Kafka.yml
samples/regio-cloud-Kafka.yml

add features list to each flavor.

---

modules/models/src/main/java/org/eclipse/xpanse/modules/models/billing/Billing.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/billing/BillingTest.java
samples/develop/flexibleEngine-compute-terraform-dev.yml
samples/develop/huawei-compute-opentofu-dev-autofill.yml
samples/develop/huawei-compute-opentofu-dev-git-repo.yml
samples/develop/huawei-compute-opentofu-dev.yml
samples/develop/huawei-compute-terraform-dev-autofill.yml
samples/develop/huawei-compute-terraform-dev-git-repo.yml
samples/develop/huawei-compute-terraform-dev.yml
samples/develop/openstack-compute-terraform-dev.yml

Add default billing mode option

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java

set default lock config for new deploy service

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceStateManager.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/1629

validate permissions for managing service state management task

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/ScriptsGitRepoManage.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/common/FlexibleEngineClient.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/common/FlexibleEngineRetryStrategy.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/manage/FlexibleEngineResourceManager.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/manage/FlexibleEngineVmStateManager.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/FlexibleEngineMetricsService.java
plugins/flexibleengine/src/test/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/FlexibleEngineMonitorIntegrationTest.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/common/HuaweiCloudClient.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/common/HuaweiCloudRetryStrategy.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/manage/HuaweiCloudResourceManager.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/manage/HuaweiCloudVmStateManager.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/monitor/HuaweiCloudMetricsService.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/price/HuaweiCloudPriceCalculator.java
plugins/huaweicloud/src/test/java/org/eclipse/xpanse/plugins/huaweicloud/monitor/HuaweiCloudMonitorIntegrationTest.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/manage/OpenstackResourceManager.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/manage/OpenstackServersManager.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/monitor/MetricsManager.java
plugins/openstack/src/test/java/org/eclipse/xpanse/plugins/openstack/monitor/OpenstackMonitoringIntegrationTest.java
plugins/scs/src/main/java/org/eclipse/xpanse/plugins/scs/manage/ScsResourceManager.java
plugins/scs/src/main/java/org/eclipse/xpanse/plugins/scs/manage/ScsServersManager.java
pom.xml
runtime/src/main/resources/application.properties
runtime/src/test/java/org/eclipse/xpanse/runtime/ExistingCloudResourcesApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceStateManageApiTest.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/1630

Add spring retry for third-party service calls

---

modules/logging/src/main/java/org/eclipse/xpanse/modules/logging/CustomRequestIdGenerator.java
runtime/src/main/resources/logback.xml

fixes https://github.com/eclipse-xpanse/xpanse/issues/1633

Add the TRACKING_ID and TASK_ID to the log

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceDeployerApi.java
modules/cache/pom.xml
modules/cache/src/main/java/org/eclipse/xpanse/modules/cache/RegionAzCacheConfig.java
modules/cache/src/main/java/org/eclipse/xpanse/modules/cache/consts/CacheNames.java
modules/pom.xml
plugins/flexibleengine/pom.xml
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/FlexibleEngineOrchestratorPlugin.java
plugins/huaweicloud/pom.xml
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/HuaweiCloudOrchestratorPlugin.java
plugins/openstack/pom.xml
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/OpenstackOrchestratorPlugin.java
plugins/scs/pom.xml
plugins/scs/src/main/java/org/eclipse/xpanse/plugins/scs/ScsOrchestratorPlugin.java
runtime/src/main/java/org/eclipse/xpanse/runtime/XpanseApplication.java
runtime/src/main/resources/application.properties

add caching for getAvailabilityZones

---

plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/common/FlexibleEngineRetryStrategy.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/manage/FlexibleEngineVmStateManager.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/common/HuaweiCloudRetryStrategy.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/manage/HuaweiCloudVmStateManager.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/1672

SDK client retry strategy use default max retry attempts

---

plugins/huaweicloud/pom.xml
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/common/HuaweiCloudClient.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/price/HuaweiCloudInternationalPriceCalculator.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/price/HuaweiCloudPriceCalculator.java
plugins/huaweicloud/src/test/java/org/eclipse/xpanse/plugins/huaweicloud/monitor/HuaweiCloudMonitorIntegrationTest.java
plugins/huaweicloud/src/test/java/org/eclipse/xpanse/plugins/huaweicloud/resourcehandler/HuaweiCloudTerraformResourceHandlerTest.java
samples/develop/huawei-compute-terraform-dev.yml

fixes https://github.com/eclipse-xpanse/xpanse/issues/1677
Users in the Chinese website get the price with currency CNY:
Users in the international website get the price with currency USD:

Get the price from international website when the specific exception is caught

---

pom.xml
runtime/pom.xml
runtime/src/test/java/org/eclipse/xpanse/runtime/openapi/OpenApiFileValidationTest.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/1697

validate openAPI doc using swagger-parser library

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceDeployerApi.java
modules/credential/src/test/java/org/eclipse/xpanse/modules/credential/DummyPluginImpl.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironmentsTest.java
modules/monitor/src/test/java/org/eclipse/xpanse/modules/monitor/ServiceMetricsAdapterTest.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/deployment/ServiceResourceHandler.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/FlexibleEngineOrchestratorPlugin.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/HuaweiCloudOrchestratorPlugin.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/OpenstackOrchestratorPlugin.java
plugins/openstack/src/main/java/org/eclipse/xpanse/plugins/openstack/manage/OpenstackResourceManager.java
plugins/scs/src/main/java/org/eclipse/xpanse/plugins/scs/ScsOrchestratorPlugin.java
plugins/scs/src/main/java/org/eclipse/xpanse/plugins/scs/manage/ScsResourceManager.java

add serviceId to getAvailabilityZones method

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceStatusChangePollingApi.java
modules/async/src/main/java/org/eclipse/xpanse/modules/async/TaskConfiguration.java
modules/async/src/test/java/org/eclipse/xpanse/modules/async/TaskConfigurationTest.java
modules/deployment/pom.xml
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/polling/StatusChangePolling.java
modules/logging/src/main/java/org/eclipse/xpanse/modules/logging/CustomRequestIdGenerator.java
modules/logging/src/main/java/org/eclipse/xpanse/modules/logging/LoggingWebFilter.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/deploy/DeploymentStatusUpdate.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/deploy/DeploymentStatusUpdateTest.java
modules/security/src/main/java/org/eclipse/xpanse/modules/security/Oauth2WebSecurityFilter.java
runtime/pom.xml
runtime/src/main/resources/application.properties
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceStatusChangePollingApiTest.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/1737

implement long-polling technique for fetching deployment status updates

---

modules/api/src/main/java/org/eclipse/xpanse/api/config/AuditLogWriter.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServicePolicyManageApi.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/policy/servicepolicy/ServicePolicyCreateRequest.java

fix error in addServicePolicy request audit

---

modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/Ocl.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/ServiceConfigurationParameter.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/OclTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/ServiceConfigurationParameterTest.java

Add service configuration parameters to OCL

---

modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/handler/DeploymentExceptionHandler.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/exceptions/DeploymentFailedException.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/response/ResultType.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceMigrationApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceModificationApiTest.java

fixes #1721 
Deploy service throws exception:
Deployment failed service in list:

deployment Apis return all exceptions

---

modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/ServiceConfigurationParameter.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/ServiceConfigurationParameterTest.java
samples/HuaweiCloud-Kafka-autofill.yml
samples/HuaweiCloud-Kafka-terraform_module.yml
samples/HuaweiCloud-Kafka.yml
samples/OpenstackTestLab-Kafka.yml
samples/PlusServer-Kafka.yml
samples/RegioCloud-Kafka.yml
samples/flexibleEngine-Kafka.yml

add new property isReadOnly to ServiceConfigurationParameter

---

plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/price/HuaweiCloudChinesePriceCalculator.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/price/HuaweiCloudPriceCalculator.java
pom.xml

Manually upgrade dependencies
Related to https://github.com/eclipse-xpanse/xpanse/pull/1792

bump huaweicloud.sdk.version from 3.1.104 to 3.1.105

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceDeployerApi.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/resource/DeployResourceEntity.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/utils/EntityTransUtils.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/resource/DatabaseDeployResourceStorageTest.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/resource/DeployResourceEntityTest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceStateManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/utils/TfResourceTransUtils.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/utils/TfResourceTransUtils.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/DeployServiceEntityConverterTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/utils/TfResourceTransUtilsTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/utils/TfResourceTransUtilsTest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/deploy/DeployResource.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/deploy/DeployResourceTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/view/DeployedServiceDetailsTest.java
modules/monitor/src/main/java/org/eclipse/xpanse/modules/monitor/ServiceMetricsAdapter.java
modules/security/src/main/java/org/eclipse/xpanse/modules/security/RequiredRoleDescriptionCustomizer.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/FlexibleEngineDataModelConverter.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/resourcehandler/FlexibleEngineTerraformResourceHandler.java
plugins/flexibleengine/src/test/java/org/eclipse/xpanse/plugins/flexibleengine/FlexibleEngineOrchestratorPluginTest.java
plugins/flexibleengine/src/test/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/FlexibleEngineMonitorIntegrationTest.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/monitor/HuaweiCloudDataModelConverter.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/resourcehandler/HuaweiCloudTerraformResourceHandler.java
plugins/huaweicloud/src/test/java/org/eclipse/xpanse/plugins/huaweicloud/HuaweiCloudOrchestratorPluginTest.java
plugins/huaweicloud/src/test/java/org/eclipse/xpanse/plugins/huaweicloud/monitor/HuaweiCloudMonitorIntegrationTest.java
plugins/openstack-common/src/main/java/org/eclipse/xpanse/plugins/openstack/common/monitor/gnocchi/utils/GnocchiToXpanseModelConverter.java
plugins/openstack-common/src/main/java/org/eclipse/xpanse/plugins/openstack/common/resourcehandler/OpenstackTerraformResourceHandler.java
plugins/openstacktestlab/src/test/java/org/eclipse/xpanse/plugins/openstacktestlab/OpenstackTestlabOrchestratorPluginTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceStateManageApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/modules/security/RequiredRoleDescriptionCustomizerTest.java

Fixed #1791
Related to https://github.com/eclipse-xpanse/xpanse-ui/pull/994
Details of the deployed service:
Call service `getComputeResourceInventoryOfService`:

Query Vm resources of the service

---

jreleaser.yml

fixes https://github.com/eclipse-xpanse/xpanse/issues/1815

enable upload release to maven central

---

modules/api/pom.xml
modules/async/pom.xml
modules/cache/pom.xml
modules/common/pom.xml
modules/credential/pom.xml
modules/database/pom.xml
modules/deployment/pom.xml
modules/logging/pom.xml
modules/models/pom.xml
modules/monitor/pom.xml
modules/observability/pom.xml
modules/orchestrator/pom.xml
modules/policy/pom.xml
modules/pom.xml
modules/security/pom.xml
modules/servicetemplate/pom.xml
modules/workflow/pom.xml
plugins/flexibleengine/pom.xml
plugins/huaweicloud/pom.xml
plugins/openstack-common/pom.xml
plugins/openstacktestlab/pom.xml
plugins/plusserver/pom.xml
plugins/pom.xml
plugins/regiocloud/pom.xml
pom.xml
runtime/pom.xml

@iskey sorry had to revert it again. Maven team claimed that all systems are working now but the uploads failed again. So had to revert the commit again

revert release version

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceDeployerApi.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ExistingCloudResourcesApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java

AZ search not returning the actual exception

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceConfigurationManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/tofumaker/TofuMakerScriptValidator.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/TerraformBootScriptValidator.java
modules/logging/src/main/java/org/eclipse/xpanse/modules/logging/CustomRequestIdGenerator.java
modules/logging/src/main/java/org/eclipse/xpanse/modules/logging/LoggingKeyConstant.java
modules/logging/src/main/java/org/eclipse/xpanse/modules/logging/LoggingWebFilter.java
runtime/src/main/resources/logback.xml

add orderID to MDC context and log lines

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java

Add retry option to deployed services

---

modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/handler/CommonExceptionHandler.java
modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/handler/ServiceMetricsExceptionHandler.java
modules/api/src/test/java/org/eclipse/xpanse/api/exceptions/handler/ServiceMetricsExceptionHandlerTest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/common/exceptions/ClientApiCallFailedException.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/common/exceptions/ClientAuthenticationFailedException.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/monitor/exceptions/ClientApiCallFailedExceptionTest.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/price/ServicePricesManager.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/common/FlexibleEngineClient.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/common/FlexibleEngineRetryStrategy.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/manage/FlexibleEngineResourceManager.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/manage/FlexibleEngineVmStateManager.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/FlexibleEngineMetricsService.java
plugins/flexibleengine/src/test/java/org/eclipse/xpanse/plugins/flexibleengine/common/FlexibleEngineClientTest.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/common/HuaweiCloudClient.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/common/HuaweiCloudRetryStrategy.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/manage/HuaweiCloudResourceManager.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/manage/HuaweiCloudVmStateManager.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/monitor/HuaweiCloudMetricsService.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/price/HuaweiCloudChinesePriceCalculator.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/price/HuaweiCloudPriceCalculator.java
plugins/openstack-common/src/main/java/org/eclipse/xpanse/plugins/openstack/common/auth/ProviderAuthInfoResolver.java
plugins/openstack-common/src/main/java/org/eclipse/xpanse/plugins/openstack/common/manage/OpenstackResourceManager.java
plugins/openstack-common/src/main/java/org/eclipse/xpanse/plugins/openstack/common/manage/OpenstackServersManager.java
plugins/openstack-common/src/main/java/org/eclipse/xpanse/plugins/openstack/common/monitor/OpenstackServiceMetricsManager.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ExistingCloudResourcesApiTest.java
samples/develop/flexibleEngine-compute-terraform-dev.yml
samples/flexibleEngine-K8S.yml
samples/flexibleEngine-Kafka.yml

Fixed #1848 
401 error in  plugin of  HuaweiCloud:
401 error in plugin of FlexibleEngine:

avoid retries for auth errors in cloud API requests

---

plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/common/HuaweiCloudClient.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/price/HuaweiCloudGlobalPriceCalculator.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/price/HuaweiCloudInternationalPriceCalculator.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/price/HuaweiCloudPriceCalculator.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/price/model/ProductInfo.java
plugins/huaweicloud/src/test/java/org/eclipse/xpanse/plugins/huaweicloud/monitor/HuaweiCloudMonitorIntegrationTest.java
pom.xml
runtime/src/main/resources/application.properties
runtime/src/test/java/org/eclipse/xpanse/runtime/ServicePricingApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/util/ApisTestCommon.java
samples/develop/HuaweiCloud-Compute-terraform-dev.yml

Fixed #1850 
Get prices with `BssintlClient` for International website:
Get prices with `BssClient` for Chinese website:
Get prices with global rest API:

handle BSS APIs not available in all regions

---

modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/handler/RegistrationExceptionHandler.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/response/ResultType.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/exceptions/UnavailableServiceRegionsException.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/OrchestratorPlugin.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/FlexibleEngineOrchestratorPlugin.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/common/FlexibleEngineConstants.java
plugins/flexibleengine/src/test/java/org/eclipse/xpanse/plugins/flexibleengine/FlexibleEngineOrchestratorPluginTest.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/HuaweiCloudOrchestratorPlugin.java
plugins/huaweicloud/src/test/java/org/eclipse/xpanse/plugins/huaweicloud/HuaweiCloudOrchestratorPluginTest.java
plugins/openstacktestlab/src/main/java/org/eclipse/xpanse/plugins/openstacktestlab/OpenstackTestlabOrchestratorPlugin.java
plugins/openstacktestlab/src/test/java/org/eclipse/xpanse/plugins/openstacktestlab/OpenstackTestlabOrchestratorPluginTest.java
plugins/plusserver/src/main/java/org/eclipse/xpanse/plugins/plusserver/PlusServerOrchestratorPlugin.java
plugins/plusserver/src/test/java/org/eclipse/xpanse/plugins/plusserver/PlusServerOrchestratorPluginTest.java
plugins/regiocloud/src/main/java/org/eclipse/xpanse/plugins/regiocloud/RegioCloudOrchestratorPlugin.java
plugins/regiocloud/src/test/java/org/eclipse/xpanse/plugins/regiocloud/RegioCloudOrchestratorPluginTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServicePricingApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceTemplateApiTest.java

Fixed https://github.com/eclipse-xpanse/xpanse/issues/1847
Unavailable region in HuaweiCloud:
Unavailable region in FlexibleEngine:

validate regions of csp in service template

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployServiceEntityConverter.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceConfigurationManager.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/DeployServiceEntityConverterTest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/AnsibleScriptConfig.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/ConfigManageScript.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/Ocl.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/ServiceConfigurationManage.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/ServiceConfigurationParameter.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/enums/ConfigurationManagerTool.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/AnsibleScriptConfigTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/ConfigManageScriptTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/OclTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/ServiceConfigurationParameterTest.java
runtime/src/main/resources/application.properties
samples/HuaweiCloud-Kafka-autofill.yml
samples/HuaweiCloud-Kafka-terraform_module.yml
samples/HuaweiCloud-Kafka.yml
samples/OpenstackTestLab-Kafka.yml
samples/PlusServer-Kafka.yml
samples/RegioCloud-Kafka.yml
samples/flexibleEngine-Kafka.yml

extend OCL to support configuration management information

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/ScriptsGitRepoManage.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/OrchestratorPlugin.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/utils/ServiceConfigurationParameterValidator.java
plugins/flexibleengine/pom.xml
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/FlexibleEngineOrchestratorPlugin.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/manage/FlexibleEngineResourceManager.java
plugins/huaweicloud/pom.xml
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/HuaweiCloudOrchestratorPlugin.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/manage/HuaweiCloudResourceManager.java
plugins/openstack-common/pom.xml
plugins/openstack-common/src/main/java/org/eclipse/xpanse/plugins/openstack/common/manage/OpenstackResourceManager.java
plugins/openstacktestlab/src/main/java/org/eclipse/xpanse/plugins/openstacktestlab/OpenstackTestlabOrchestratorPlugin.java
plugins/plusserver/src/main/java/org/eclipse/xpanse/plugins/plusserver/PlusServerOrchestratorPlugin.java
plugins/regiocloud/src/main/java/org/eclipse/xpanse/plugins/regiocloud/RegioCloudOrchestratorPlugin.java
pom.xml

ServiceConfigurationParameter - Extend the parameter with resource information

---

samples/HuaweiCloud-Kafka-autofill.yml
samples/HuaweiCloud-Kafka-terraform_module.yml
samples/HuaweiCloud-Kafka.yml

Fix price error when using templates of kafka service

Update error billing config in the templates for kafka service

---

modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialOpenApiGenerator.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/utils/ServiceTemplateOpenApiGenerator.java
runtime/src/test/java/org/eclipse/xpanse/runtime/modules/servicetemplate/utils/ServiceTemplateOpenApiGeneratorTest.java

Update doc of the open API `deploy`:
Update doc of the open API `addUserCredential`:

Update docs of open API

---

modules/database/src/main/java/org/eclipse/xpanse/modules/database/utils/EntityTransUtils.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/view/DeployedService.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/view/DeployedServiceTest.java

add region and billingmode for deployedService.

---

modules/cache/src/main/java/org/eclipse/xpanse/modules/cache/RedisCacheConfig.java
modules/cache/src/main/java/org/eclipse/xpanse/modules/cache/consts/CacheConstants.java
modules/cache/src/main/java/org/eclipse/xpanse/modules/cache/credential/CredentialsStore.java

Fixed https://github.com/eclipse-xpanse/xpanse/issues/1932

fix error ttl time of credential redis cache

---

modules/api/src/main/java/org/eclipse/xpanse/api/config/ServiceTemplateEntityConverter.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/EndUserFlavors.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/view/UserOrderableServiceVo.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/view/UserOrderableServiceVoTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceCatalogApiTest.java

update flavor of orderable service details api for end user.

---

modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceconfiguration/update/ServiceConfigurationUpdateRepository.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceConfigurationManager.java

add distributed locking mechanism for requests from agents

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/AgentPollingApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/handler/ServiceConfigurationExceptionHandler.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceconfiguration/update/DatabaseServiceConfigurationUpdateStorage.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceconfiguration/update/ServiceConfigurationUpdateStorage.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceConfigurationManager.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/response/ResultType.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/serviceconfiguration/AnsibleTaskResult.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/serviceconfiguration/ServiceConfigurationChangeResult.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/serviceconfiguration/exceptions/ServiceConfigurationUpdateRequestNotFoundException.java
modules/security/src/main/java/org/eclipse/xpanse/modules/security/Oauth2WebSecurityFilter.java

create updateConfigurationChangeResult for agent to update result

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceConfigurationManager.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/ServiceConfigurationManagerTest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/serviceconfiguration/ServiceConfigurationChangeRequest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/serviceconfiguration/ServiceConfigurationChangeRequestTest.java

change ServiceConfigurationChangeRequest to use changeId instead of orderId

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceConfigurationApi.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/utils/EntityTransUtils.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceConfigurationManager.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/serviceconfiguration/ServiceConfigurationChangeRequestDetails.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/serviceconfiguration/ServiceConfigurationUpdateRequestOrderDetails.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceConfigurationApiTest.java

fix listServiceConfigurationUpdateRequest method

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/opentofulocal/OpenTofuLocalDeployment.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/tofumaker/TofuMakerHelper.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/TerraformBootHelper.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformlocal/TerraformLocalDeployment.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironments.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/opentofulocal/OpenTofuLocalDeploymentTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/tofumaker/TofuMakerDeploymentTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/TerraformBootDeploymentTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformlocal/TerraformLocalDeploymentTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironmentsTest.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/1991

pass service id as an environment variable to deployers

---

modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/AnsibleScriptConfig.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/AnsibleScriptConfigTest.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/2010

change python version type to string

---

runtime/src/test/java/org/eclipse/xpanse/runtime/modules/servicetemplate/utils/ServiceTemplateOpenApiGeneratorTest.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/2014

fix flaky test

---

modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceconfiguration/update/ServiceConfigurationChangeDetailsEntity.java

SERVICE_CONFIGURATION_UPDATE_REQUEST table shows only one FK index

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceConfigurationManager.java

update SERVICE_CONFIGURATION table after completion of config update request

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironments.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironmentsTest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/AnsibleScriptConfig.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/ServiceConfigurationManage.java
runtime/src/main/resources/application.properties

fixes https://github.com/eclipse-xpanse/xpanse/issues/2006

add agent version and url as variables to deployer

---

.github/workflows/release.yml
Dockerfile
install_opentofu.sh
install_terraform.sh
start-xpanse-with-private_key.sh

Build docker image and run a container successfully:
Installed multiple versions of Terraform and OpenTofu:

Install multiple versions of Terraform and OpenTofu during Docker build

---

modules/api/src/main/java/org/eclipse/xpanse/api/config/GetCspInfoFromRequest.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/CustomJpaRepository.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DatabaseDeployServiceStorage.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DeployServiceEntity.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DeployServiceStorage.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceorder/DatabaseServiceOrderStorage.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceorder/ServiceOrderEntity.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/utils/EntityTransUtils.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/serviceorder/DatabaseServiceOrderStorageTest.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/serviceorder/ServiceOrderEntityTest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceConfigurationManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceOrderManager.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/ServiceConfigurationManagerTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceOrderManageApiTest.java

make SERVICE_ID column as FK in SERVICE_ORDER table

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/AgentPollingApi.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceconfiguration/update/ServiceConfigurationChangeDetailsEntity.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/serviceconfiguration/ServiceConfigurationChangeDetailsEntityTest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceConfigurationManager.java

fix updateConfigurationChangeResult return code and store task information

---

modules/api/src/main/java/org/eclipse/xpanse/api/config/ServiceTemplateEntityConverter.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/view/ServiceTemplateDetailVo.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/view/UserOrderableServiceVo.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/view/ServiceTemplateDetailVoTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/view/UserOrderableServiceVoTest.java

return service configuration information for different roles

---

modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/utils/ServiceConfigurationParameterValidator.java

use all files in GIT repo for finding compute resources

---

modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DeployServiceEntity.java

remove cascade from child to parent table

---

modules/api/src/test/java/org/eclipse/xpanse/api/exceptions/handler/CommonExceptionHandlerTest.java
pom.xml

dependencies: bump org.springframework.boot:spring-boot-starter-parent from 3.3.4 to 3.3.5

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceDeployerApi.java
modules/api/src/test/java/org/eclipse/xpanse/api/exceptions/handler/DeploymentExceptionHandlerTest.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceorder/ServiceOrderEntity.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/serviceorder/ServiceOrderEntityTest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployServiceEntityConverter.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceOrderManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/servicelock/ServiceLockConfigService.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/DeployServiceEntityConverterTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/tofumaker/TofuMakerDeploymentTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/TerraformBootDeploymentTest.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/deployment/DeployTask.java
modules/orchestrator/src/test/java/org/eclipse/xpanse/modules/orchestrator/deployment/DeployTaskTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java

Fixed https://github.com/eclipse-xpanse/xpanse/issues/2058

use service_order table for lock/unlock requests

---

modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/ServiceDeploymentEntity.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/utils/EntityTransUtils.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/service/ServiceDeploymentEntityTest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceOrderManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/callbacks/OpenTofuDeploymentResultCallbackManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/utils/TfResourceTransUtils.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/callbacks/TerraformDeploymentResultCallbackManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/utils/TfResourceTransUtils.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/opentofulocal/OpenTofuLocalDeploymentTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformlocal/TerraformLocalDeploymentTest.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/deployment/DeployResult.java
modules/orchestrator/src/test/java/org/eclipse/xpanse/modules/orchestrator/deployment/DeployResultTest.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/resourcehandler/FlexibleEngineTerraformResourceHandler.java
plugins/flexibleengine/src/test/java/org/eclipse/xpanse/plugins/flexibleengine/reourcehandler/FlexibleEngineTerraformResourceHandlerTest.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/resourcehandler/HuaweiCloudTerraformResourceHandler.java
plugins/huaweicloud/src/test/java/org/eclipse/xpanse/plugins/huaweicloud/resourcehandler/HuaweiCloudTerraformResourceHandlerTest.java
plugins/openstack-common/src/main/java/org/eclipse/xpanse/plugins/openstack/common/resourcehandler/OpenstackTerraformResourceHandler.java
plugins/openstack-common/src/test/java/org/eclipse/xpanse/plugins/openstack/common/resourcehandler/OpenstackTerraformResourceHandlerTest.java

fixes #2067 
rename properties -> outputProperties,privateProperties -> deploymentGeneratedFiles

rename properties, privateProperties

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceMigrationApi.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/migration/steps/ProcessDeploymentResult.java

update migrate service api.

---

runtime/src/main/resources/application-zitadel-testbed.properties

Fixed https://github.com/eclipse-xpanse/xpanse/issues/2121
Related to https://github.com/eclipse-xpanse/xpanse-ui/pull/1280

Update oauth2 configs of zitadel-testbed

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/resources/TfOutput.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/resources/TfOutput.java
runtime/src/test/java/org/eclipse/xpanse/runtime/OpenTofuMakerWebhookApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceConfigurationApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceStateManageApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/TerraformBootWebhookApiTest.java

**Fixed https://github.com/eclipse-xpanse/xpanse/issues/2120
Related to https://github.com/eclipse-xpanse/xpanse-samples/pull/12**
Deploy MySql service successfully:

Fix deployment state always is deploying when deploy a MySql service instance

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceTemplateApi.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicetemplate/DatabaseServiceTemplateStorage.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicetemplatehistory/ServiceTemplateHistoryEntity.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/DeployerTool.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/FlavorsWithPrice.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/ServiceProviderContactDetails.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplatechange/ServiceTemplateChangeInfo.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java
runtime/src/test/java/org/eclipse/xpanse/runtime/CspServiceTemplateApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServicePricingApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceTemplateApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/database/mysql/DeploymentWithMysqlTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/database/mysql/RegistrationWithMysqlTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/util/ApisTestCommon.java

**Fixed #2100** 
**Register service template :**

implement changes to service template registration method

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceOrderManageApiTest.java

update order progress when task execution completes.

---

modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/order/ServiceOrderDetails.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/order/ServiceOrderDetailsTest.java

switch errorMsg's type to ErrorResponse for ServiceOrderDetails.

---

modules/common/src/main/java/org/eclipse/xpanse/common/proxy/ProxyConfigurationManager.java
modules/common/src/main/java/org/eclipse/xpanse/common/proxy/ProxyDetails.java
modules/common/src/main/java/org/eclipse/xpanse/common/proxy/ProxyVariables.java
modules/common/src/main/java/org/eclipse/xpanse/common/systemcmd/SystemCmd.java
modules/common/src/test/java/org/eclipse/xpanse/common/systemcmd/ProxyConfigurationManagerTest.java
modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialCenter.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/deployertools/DeployerToolVersionsFetcher.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/common/HuaweiCloudClient.java
plugins/huaweicloud/src/test/java/org/eclipse/xpanse/plugins/huaweicloud/monitor/HuaweiCloudMonitorIntegrationTest.java
plugins/openstack-common/src/main/java/org/eclipse/xpanse/plugins/openstack/common/auth/constants/OpenstackCommonEnvironmentConstants.java
plugins/openstack-common/src/main/java/org/eclipse/xpanse/plugins/openstack/common/auth/keystone/OpenstackKeystoneManager.java
plugins/openstack-common/src/main/java/org/eclipse/xpanse/plugins/openstack/common/auth/keystone/ScsKeystoneManager.java
plugins/openstacktestlab/src/test/java/org/eclipse/xpanse/plugins/openstacktestlab/OpenstackTestlabOrchestratorPluginTest.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/2155

implement common proxy configuration for all interfaces

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceDeployerApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceTemplateApi.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceconfiguration/update/ServiceConfigurationChangeDetailsEntity.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceorder/ServiceOrderEntity.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironments.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/deployment/ServiceResourceHandler.java
plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/FlexibleEngineOrchestratorPlugin.java
plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/HuaweiCloudOrchestratorPlugin.java
plugins/openstack-common/src/main/java/org/eclipse/xpanse/plugins/openstack/common/auth/ProviderAuthInfoResolver.java
plugins/openstack-common/src/main/java/org/eclipse/xpanse/plugins/openstack/common/manage/OpenstackResourceManager.java
plugins/openstack-common/src/main/java/org/eclipse/xpanse/plugins/openstack/common/manage/OpenstackServersManager.java
plugins/openstack-common/src/main/java/org/eclipse/xpanse/plugins/openstack/common/monitor/OpenstackServiceMetricsManager.java
plugins/openstacktestlab/src/main/java/org/eclipse/xpanse/plugins/openstacktestlab/OpenstackTestlabOrchestratorPlugin.java
plugins/openstacktestlab/src/test/java/org/eclipse/xpanse/plugins/openstacktestlab/OpenstackTestlabOrchestratorPluginTest.java
plugins/plusserver/src/main/java/org/eclipse/xpanse/plugins/plusserver/PlusServerOrchestratorPlugin.java
plugins/plusserver/src/test/java/org/eclipse/xpanse/plugins/plusserver/PlusServerOrchestratorPluginTest.java
plugins/regiocloud/src/main/java/org/eclipse/xpanse/plugins/regiocloud/RegioCloudOrchestratorPlugin.java
plugins/regiocloud/src/test/java/org/eclipse/xpanse/plugins/regiocloud/RegioCloudOrchestratorPluginTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/database/mysql/DeploymentWithMysqlTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/database/mysql/RegistrationWithMysqlTest.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/2160

allow fetching of plugin variables from service templates

---

modules/security/pom.xml
modules/security/src/main/java/org/eclipse/xpanse/modules/security/Oauth2JwtConfig.java
modules/security/src/main/java/org/eclipse/xpanse/modules/security/Oauth2JwtDecoder.java
modules/security/src/main/java/org/eclipse/xpanse/modules/security/Oauth2WebSecurityFilter.java
pom.xml

Fixed https://github.com/eclipse-xpanse/xpanse/issues/2178
Related to https://github.com/eclipse-xpanse/tofu-maker/pull/89
Related to https://github.com/eclipse-xpanse/terraform-boot/pull/171
When connect to IAM server failed will retry:

Add retry for JWT auth to void application startup failed

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/view/UserOrderableServiceVo.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/view/UserOrderableServiceVoTest.java
modules/security/src/main/java/org/eclipse/xpanse/modules/security/UserServiceHelper.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java
runtime/src/test/resources/jwt_all_roles-no-policies.json
runtime/src/test/resources/jwt_all_roles.json
runtime/src/test/resources/jwt_csp_isv_user.json
runtime/src/test/resources/jwt_isv.json
runtime/src/test/resources/jwt_user.json

fixes #2176 
1.register with same namespace:
get namespace from UserOrderableServiceVo same with template:
2.register with diff namespace:
3.register when user's namespace is empty

add namespace for UserOrderableServiceVo.

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceMigrationApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceRecreateApi.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceorder/ServiceOrderEntity.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/serviceorder/ServiceOrderEntityTest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceConfigurationManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceDetailsViewManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceOrderManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceResultReFetchManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceStateManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/callbacks/OpenTofuDeploymentResultCallbackManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/tofumaker/TofuMakerResultRefetchManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/callbacks/TerraformDeploymentResultCallbackManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/TerraformBootResultRefetchManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/servicelock/ServiceLockConfigService.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/tofumaker/TofuMakerDeploymentTest.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/TerraformBootDeploymentTest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/enums/Handler.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/order/ServiceOrderDetails.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/order/ServiceOrderDetailsTest.java
runtime/src/main/resources/application.properties
runtime/src/test/java/org/eclipse/xpanse/runtime/util/ApisTestCommon.java

Integrate getStoredTaskResultByRequestId in xpanse

---

modules/api/src/main/java/org/eclipse/xpanse/api/config/ServiceTemplateEntityConverter.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployServiceEntityConverter.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceConfigurationManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceDetailsViewManager.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/ServiceDeploymentEntityConverterTest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/utils/ServiceConfigurationVariablesJsonSchemaGenerator.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/utils/ServiceConfigurationVariablesJsonSchemaValidator.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/Ocl.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/ServiceChangeManage.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/ServiceChangeParameter.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/ServiceChangeScript.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/view/ServiceTemplateDetailVo.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/view/UserOrderableServiceVo.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/OclTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/ServiceChangeParameterTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/ServiceChangeScriptTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/view/ServiceTemplateDetailVoTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/view/UserOrderableServiceVoTest.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/utils/ServiceConfigurationParameterValidator.java
runtime/src/test/resources/ocl_terraform_kafka_test.yml

change service configuration related data model names to common names

---

modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/handler/RegistrationExceptionHandler.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/response/ErrorType.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/exceptions/MandatoryValueMissingForFixedVariablesException.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/utils/DeployVariableSchemaValidator.java

Add validation for variable kind - fix_env and fix_variable.

---

modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/handler/ServiceActionExceptionHandler.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/response/ErrorType.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/serviceconfiguration/exceptions/ServiceActionTemplateInvalidException.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/Ocl.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/ServiceAction.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/OclTest.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/utils/ServiceActionTemplateValidator.java

extend OCL to support service actions.

---

modules/database/src/main/java/org/eclipse/xpanse/modules/database/EnumColumnAllowedValuesUpdater.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/enumcolumn/EnumColumnConstraintManage.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/userpolicy/UserPolicyEntity.java
pom.xml

Fixed https://github.com/eclipse-xpanse/xpanse/issues/2222
Startup the application after code updated, the values of enum column in H2 DB updated too:

Update method to update values of enum columns in H2 DB

---

modules/api/src/main/java/org/eclipse/xpanse/api/config/GetCspInfoFromRequest.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/IsvServiceDeployApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceConfigurationApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceDeployerApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceMetricsApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceOrderManageApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServicePolicyManageApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceRecreateApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceStateManageApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/UserPolicyManageApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/WorkFlowApi.java
modules/api/src/test/java/org/eclipse/xpanse/api/exceptions/handler/ServiceMetricsExceptionHandlerTest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceConfigurationManager.java
modules/monitor/src/main/java/org/eclipse/xpanse/modules/monitor/ServiceMetricsAdapter.java
modules/policy/src/main/java/org/eclipse/xpanse/modules/policy/ServicePolicyManager.java
modules/policy/src/main/java/org/eclipse/xpanse/modules/policy/UserPolicyManager.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceMetricsApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/database/mysql/DeploymentWithMysqlTest.java

change all ID parameters in URI to UUID.

---

modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicetemplaterequest/ServiceTemplateRequestHistoryEntity.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/ReviewServiceTemplateRequest.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java
runtime/src/test/java/org/eclipse/xpanse/runtime/CspServiceTemplateApiTest.java

add validation for review comment.

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
modules/models/src/main/java/org/eclipse/xpanse/modules/models/policy/servicepolicy/ServicePolicyUpdateRequest.java

Fixed https://github.com/eclipse-xpanse/xpanse/issues/2245

update service policy allows empty flavor name list

---

modules/api/src/main/java/org/eclipse/xpanse/api/config/GetCspInfoFromRequest.java
modules/api/src/main/java/org/eclipse/xpanse/api/config/ServiceTemplateEntityConverter.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ExistingCloudResourcesApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/OpenTofuMakerWebhookApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceCatalogApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServicePolicyManageApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServicePricingApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/TerraformBootWebhookApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/UserPolicyManageApi.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/userpolicy/DatabaseUserPolicyStorage.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/userpolicy/UserPolicyStorage.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/userpolicy/DatabaseUserPolicyStorageTest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/PolicyValidator.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceStateManager.java
modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/price/ServiceFlavorPriceRequest.java
modules/orchestrator/src/test/java/org/eclipse/xpanse/modules/orchestrator/price/FlavorPriceResultRequestTest.java
modules/policy/src/main/java/org/eclipse/xpanse/modules/policy/ServicePolicyManager.java
modules/policy/src/main/java/org/eclipse/xpanse/modules/policy/UserPolicyManager.java
modules/policy/src/test/java/org/eclipse/xpanse/modules/policy/policyman/ServicePolicyManagerTest.java
modules/policy/src/test/java/org/eclipse/xpanse/modules/policy/policyman/UserPolicyManagerTest.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/price/ServicePricesManager.java
plugins/openstacktestlab/src/test/java/org/eclipse/xpanse/plugins/openstacktestlab/OpenstackTestlabOrchestratorPluginTest.java
plugins/plusserver/src/test/java/org/eclipse/xpanse/plugins/plusserver/PlusServerOrchestratorPluginTest.java
plugins/regiocloud/src/test/java/org/eclipse/xpanse/plugins/regiocloud/RegioCloudOrchestratorPluginTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceTemplateApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/openapi/OpenApiFileValidationTest.java

Fixed https://github.com/eclipse-xpanse/xpanse/issues/2204
Related to https://github.com/eclipse-xpanse/xpanse-ui/pull/1393

change all ID parameters in URI to UUID

---

modules/cache/src/main/java/org/eclipse/xpanse/modules/cache/RedisCacheConfig.java

Fixed https://github.com/eclipse-xpanse/xpanse/issues/2260

Get cached service flavor price from Redis

---

modules/models/src/main/java/org/eclipse/xpanse/modules/models/workflow/WorkFlowTask.java

Fixed https://github.com/eclipse-xpanse/xpanse/issues/2268

fix query tasks error

---

modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicetemplaterequest/ServiceTemplateRequestHistoryEntity.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/2279

remove dummy review comment

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/AgentPollingApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceChangeDetailsApi.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceconfiguration/update/ServiceChangeDetailsEntity.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceconfiguration/update/ServiceChangeDetailsQueryModel.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/serviceconfiguration/DatabaseServiceChangeDetailsStorageTest.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/serviceconfiguration/ServiceChangeDetailsEntityTest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceChangeDetailsManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceConfigurationManager.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/serviceconfiguration/ServiceChangeDetails.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/serviceconfiguration/ServiceChangeRequest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/serviceconfiguration/enums/ServiceChangeStatus.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/serviceconfiguration/ServiceChangeRequestTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceConfigurationApiTest.java

changes to polling APIs to allow polling all types of requests

---

modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/utils/DeployVariableSchemaValidator.java
modules/servicetemplate/src/test/java/org/eclipse/xpanse/modules/servicetemplate/utils/DeployVariableSchemaValidatorTest.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/2295

fix validation of fix_env and fix_variable deploy variable

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/CspServiceTemplateApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceTemplateApi.java
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java
runtime/src/test/java/org/eclipse/xpanse/runtime/database/mysql/RegistrationWithMysqlTest.java

add service template history service to CSP user

---

runtime/src/main/resources/application-zitadel-local.properties
runtime/src/main/resources/application.properties
runtime/src/test/java/org/eclipse/xpanse/runtime/modules/deployment/OpenTofuInstallerTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/modules/deployment/TerraformInstallerTest.java

related to https://github.com/eclipse-xpanse/xpanse/issues/2285

add new zitadel local instance configuration for development

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/CspServiceDeployApi.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceDetailsViewManager.java

Registered Services Page Called Error API for ISV user

---

modules/api/src/main/java/org/eclipse/xpanse/api/config/ServiceTemplateEntityConverter.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceDetailsViewManager.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/ServiceChangeParameter.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/view/UserOrderableServiceVo.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/view/UserOrderableServiceVoTest.java

add service actions to UI

---

modules/database/pom.xml
modules/database/src/main/java/org/eclipse/xpanse/modules/database/resource/ServiceResourceEntity.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/ServiceDeploymentEntity.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicechange/ServiceChangeDetailsEntity.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceconfiguration/ServiceConfigurationEntity.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicepolicy/ServicePolicyEntity.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicetemplate/ServiceTemplateEntity.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicetemplaterequest/ServiceTemplateRequestHistoryEntity.java
modules/database/src/main/resources/liquibase/full/h2/xpanse-1.0.24-full.h2.xml
modules/database/src/main/resources/liquibase/full/mysql/xpanse-1.0.24-full.mysql.xml
modules/database/src/main/resources/liquibase/liquibase.h2.properties
modules/database/src/main/resources/liquibase/liquibase.mysql.properties
pom.xml
runtime/src/main/resources/application.properties

fixes https://github.com/eclipse-xpanse/xpanse/issues/2313

introduce liquibase for database schema management

---

modules/logging/src/main/java/org/eclipse/xpanse/modules/logging/RestTemplateLoggingInterceptor.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/2351

fix rest request logger to log in correct sequence

---

modules/security/src/main/java/org/eclipse/xpanse/modules/security/secrets/SecretsManager.java
modules/security/src/test/java/org/eclipse/xpanse/modules/security/secrets/SecretsManagerTest.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/2368

fix secret encryption to generate new object for each thread

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/tofumaker/TofuMakerResultRefetchManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/TerraformBootResultRefetchManager.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/2374

handle all errors from deployer tools while re-fetching missing results

---

modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/handler/CommonExceptionHandler.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/2381

handle unknown URL errors and return 404

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceResultReFetchManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/tofumaker/TofuMakerResultRefetchManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/TerraformBootResultRefetchManager.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/2385

fix result refetching to fetch the correct in-progress order

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/tofumaker/TofuMakerResultRefetchManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraboot/TerraBootResultRefetchManager.java
runtime/src/main/resources/application-zitadel-local.properties

fixes https://github.com/eclipse-xpanse/xpanse/issues/2399

fix refetch to update deployment state and process the result

---

modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialCenter.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/2401

decrypting fixed to be done only for credentials in cache

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceConfigurationApiTest.java

fix service config after deployed success

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceActionsApi.java
modules/api/src/test/java/org/eclipse/xpanse/api/annotations/AgentAnnotationTest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicechange/AnsibleTaskResult.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicechange/ServiceChangeRequest.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicechange/ServiceChangeResult.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/2433

add missing conditional annotations to actions API

---

.github/workflows/move-issue-status-assigned.yml
.github/workflows/move-issue-status-unassigned.yml

fixes https://github.com/eclipse-xpanse/xpanse/issues/2444

add project workflow automation

---

modules/api/src/main/java/org/eclipse/xpanse/api/config/ServiceTemplateEntityConverter.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/view/ServiceTemplateDetailVo.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/view/ServiceTemplateDetailVoTest.java

add serviceActions for ServiceTemplateDetailVo.

---

modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicechange/ServiceChangeRequestEntity.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/serviceconfiguration/ServiceChangeRequestEntityTest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceChangeManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceChangeRequestsManager.java

add CREATED_TIME and UPDATED_TIME to ServiceChangeRequestEntity

---

modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/handler/ServiceConfigurationExceptionHandler.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceConfigurationManager.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/response/ErrorType.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/serviceconfiguration/exceptions/ServiceConfigChangeOrderAlreadyExistsException.java

changeServiceConfiguration allows multiple config change requests

---

modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/handler/ServiceConfigurationExceptionHandler.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceActionManager.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/response/ErrorType.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/serviceconfiguration/exceptions/ServiceActionChangeOrderAlreadyExistsException.java

add validation for pending service action orders in createServiceAction

---

modules/api/src/main/java/org/eclipse/xpanse/api/config/DatasourceConfig.java
modules/workflow/src/main/java/org/eclipse/xpanse/modules/workflow/config/ActivitiConfig.java
runtime/src/main/java/org/eclipse/xpanse/runtime/XpanseApplication.java
runtime/src/main/resources/application-mysql.properties
runtime/src/main/resources/application.properties
runtime/src/test/java/org/eclipse/xpanse/runtime/database/mysql/AbstractMysqlIntegrationTest.java

Fixed #2318
H2:
recreate
port
MySql:
recreate:
port:

split datasources between xpanse and activiti

---

modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/ObjectIdentifier.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/ObjectManage.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/ObjectParameter.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/Ocl.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/ServiceObject.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/enums/ObjectActionType.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/ObjectIdentifierTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/ObjectManageTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/ObjectParameterTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/OclTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/ServiceObjectTest.java

Introduce service objects data models to OCL

---

modules/api/src/main/java/org/eclipse/xpanse/api/config/GetCspInfoFromRequest.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServicePortingApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceRecreateApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/handler/DeploymentExceptionHandler.java
modules/api/src/test/java/org/eclipse/xpanse/api/exceptions/handler/DeploymentExceptionHandlerTest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceActionManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceConfigurationManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceDeploymentEntityConverter.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceDeploymentEntityHandler.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceDetailsViewManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceOrderManager.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceStateManager.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/response/ErrorType.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/deployment/exceptions/InvalidServiceDeploymentStateException.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceOrderManageApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceRecreateApiTest.java
runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceStateManageApiTest.java

Fixed https://github.com/eclipse-xpanse/xpanse/issues/2509
Related to https://github.com/eclipse-xpanse/xpanse-ui/pull/1615

Validate Service Deployment State for order requests

---

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/AgentPollingApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceActionsApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceChangeRequestDetailsApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceObjectsApi.java
modules/api/src/main/java/org/eclipse/xpanse/api/controllers/TofuMakerWebhookApi.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceobject/DatabaseServiceObjectStorage.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceobject/ServiceObjectEntity.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceobject/ServiceObjectStorage.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceorder/DatabaseServiceOrderStorage.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceorder/ServiceOrderStorage.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/utils/EntityTranslationUtils.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/serviceobject/ServiceObjectEntityTest.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceObjectManager.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/common/enums/UserOperation.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/serviceobject/ServiceObjectDetails.java
runtime/src/test/java/org/eclipse/xpanse/runtime/TofuMakerWebhookApiTest.java

Fixed https://github.com/eclipse-xpanse/xpanse/issues/2489
Request new API GetObjectsByServiceId:

create new API GetObjectsByServiceId

---

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/enums/ServiceDeploymentState.java

fixes https://github.com/eclipse-xpanse/xpanse/issues/2578

fix status update after rollback is successful

---

modules/ai/src/main/resources/templates/mcp/mcp-ecs-with-service-template.yml.peb
modules/api/src/test/resources/ocl_terraform_test.yml
modules/common/src/main/java/org/eclipse/xpanse/common/proxy/ProxyConfigurationManager.java
modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicetemplate/ServiceTemplateEntity.java
modules/database/src/test/java/org/eclipse/xpanse/modules/database/servicetemplate/ServiceTemplateEntityTest.java
modules/database/src/test/resources/ocl_terraform_test.yml
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/deployertools/DeployerTarGzFileManage.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/deployertools/DeployerToolUtils.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/deployertools/DeployerToolVersionsFetcher.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/deployertools/DeployerZipFileManage.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/helm/installer/HelmBinaryInstaller.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/opentofulocal/OpenTofuInstaller.java
modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformlocal/TerraformInstaller.java
modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/helm/HelmBinaryInstallerTest.java
modules/deployment/src/test/resources/ocl_terraform_from_git_test.yml
modules/deployment/src/test/resources/ocl_terraform_test.yml
modules/models/src/main/java/org/eclipse/xpanse/modules/models/common/exceptions/RateLimiterException.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/Ocl.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/view/ServiceTemplateDetailVo.java
modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/view/UserOrderableServiceVo.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/OclTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/view/ServiceTemplateDetailVoTest.java
modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/view/UserOrderableServiceVoTest.java
modules/models/src/test/resources/ocl_helm_test.yml
modules/models/src/test/resources/ocl_terraform_test.yml
modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java
modules/servicetemplate/src/test/resources/ocl_terraform_test.yml
runtime/src/test/resources/ocl_terraform_from_git_test.yml
runtime/src/test/resources/ocl_terraform_kafka_test.yml
runtime/src/test/resources/ocl_terraform_test.yml

fixes https://github.com/eclipse-xpanse/xpanse/issues/2635

add shortcode to OCL
