eclipse-xpanse/xpanse

services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/BaseImage.java, services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/BaseImageFilter.java, services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/Image.java, services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/Ocl.java, services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/Provisioner.java, services/ocl-loader/src/test/java/org/eclipse/osc/services/ocl/loader/OclLoaderTest.java, services/ocl-loader/src/test/resources/test.json
What this PR does / why we need it:
Add a customized `JsonPath` parser for OCL.
Align the basic classes to OCL.
Which issue this PR fixes:
Resolves #26  resolves #18
=> Add a customized JsonPath parser for OCL.

services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/Artifact.java, services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/Security.java, services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/SecurityRule.java, services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/Storage.java, services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/Subnet.java, services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/VM.java, services/ocl-loader/src/main/java/org/eclipse/osc/services/ocl/loader/VPC.java, services/ocl-loader/src/test/java/org/eclipse/osc/services/ocl/loader/StorageTest.java
The previous Data Object's equals and hashcode code generation have bugs, it doesn't call super() so two object will be equals even the property inherited from super is not equals. 
For example:
<code>
@Data
public class Storage extends RuntimeBase {
private String name;
private String type;
private String size;
}
</code>
will have the wrong behavior:
Storage storage = new Storage();
Storage anotherStorage = new Storage();
storage.setState("some state");
anotherStorage.setState("another state");
storage.setName("sameName");
anotherStorage.setName("sameName");
Assertions.Equals(storage, anotherStorage); //this line return true and the test can pass, which is wrong.
=> Bugfix: fix the equals and hashCode method of data object when they extended a base data object

checkstyle.xml, pom.xml
1. Allow suppressing warnings by adding inline comments. 
2. remove wrong license plugin
3. Move license  header file  as config to plugin. This will allow maven sub modules to also validate header files.
=> add config to suppress warnings

modules/api/pom.xml, modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/CommonExceptionHandler.java, modules/api/src/main/java/org/eclipse/xpanse/api/response/ResponseValidator.java, modules/api/src/main/java/org/eclipse/xpanse/api/response/ResultType.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/exceptions/ResponseInvalidException.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/DeployResult.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/view/CategoryOclVo.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/view/ProviderOclVo.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/view/ServiceDetailVo.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/view/UserAvailableServiceVo.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/view/VersionOclVo.java
Fixes #300 
With this change, the API will not return anything that does not match to our own Schema. If response is bad we return the bean validation errors back.
=> validate response beans with schema definition

modules/models/src/main/java/org/eclipse/xpanse/modules/models/view/ServiceVo.java
This is a bug. When we add Notblank on enums, the response validation fails. Notblank is only for strings.
=> remove wrong validator on enum field

modules/api/src/main/java/org/eclipse/xpanse/api/OrchestratorApi.java
Current return type is not clear for clients. We must return a proper type.
=> return a proper object to avoid client breaking

modules/api/src/main/java/org/eclipse/xpanse/api/CredentialManageApi.java, modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialCenter.java
Default value for the "value" field in credential definition must be filled only for the getCredentialCapabilitiesByCsp API method. 
In the current version, the value is set always and it is causing null checks to always fail.
Related to #423
=> fill default value field only for API calls

modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialCenter.java, runtime/src/test/java/org/eclipse/xpanse/runtime/CredentialManageApiTest.java
=> Fix getCredentialsByUser API return value not masking sensitive values

modules/api/pom.xml, modules/api/src/main/java/org/eclipse/xpanse/api/config/OpenApiCustomizerConfig.java, modules/database/src/test/java/org/eclipse/xpanse/modules/database/utils/EntityTransUtilsTest.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformBootDeployment.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeployment.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformExecutor.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironments.java, modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/DeployServiceTest.java, modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformBootDeploymentTest.java, modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeploymentTest.java, modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironmentsTest.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/credential/AbstractCredentialInfo.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/deploy/DeployRequestBase.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/utils/ServiceVariablesJsonSchemaValidator.java, modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/deploy/DeployRequestTest.java, modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/utils/ServiceVariablesJsonSchemaGeneratorAndValidatorTest.java, modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/view/ServiceDetailVoTest.java, modules/security/src/main/java/org/eclipse/xpanse/modules/security/common/AesUtil.java, runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java, runtime/src/test/java/org/eclipse/xpanse/runtime/database/mysql/DeploymentWithMysqlTest.java
fixes https://github.com/eclipse-xpanse/xpanse/issues/962
`serviceRequestProperties` now accepts all possible datatypes.
```json
{
"category":"middleware",
"csp":"scs",
"flavor":"1-zookeeper-with-3-worker-nodes-normal",
"region":"RegionOne",
"serviceName":"kafka-cluster",
"version":"v1.0.0",
"customerServiceName":"u500924-swaroopar",
"serviceRequestProperties":{
"secgroup_name_boolean":true,
"subnet_name":"dfdfdfdf",
"secgroup_name_integer":100
}
}
```
=> handle all types in service deployment properties

modules/api/src/test/java/org/eclipse/xpanse/api/exceptions/handler/PolicyManageExceptionHandlerTest.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/policy/exceptions/PoliciesValidationFailedException.java
fixes #1037 
Before:
{
"resultType": "Policy Validation Failed",
"details": [
"Policy is invalid. Error reasons: I/O error on POST request for \"http://localhost:8090/validate/policies\": Connection refused"
],
"success": false
}
Updated :
{
"resultType": "Policy Validation Failed",
"details": [
"I/O error on POST request for \"http://localhost:8090/validate/policies\": Connection refused: connect"
],
"success": false
}
=> update error message when policy validation failed

modules/database/src/main/java/org/eclipse/xpanse/modules/database/DatabaseManager.java, modules/database/src/main/java/org/eclipse/xpanse/modules/database/EnumColumnAllowedValuesUpdater.java, modules/database/src/main/java/org/eclipse/xpanse/modules/database/enumcolumn/EnumColumnConstraintManage.java, modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DatabaseDeployServiceStorage.java, modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/DeployServiceEntity.java, modules/database/src/test/java/org/eclipse/xpanse/modules/database/service/DatabaseDeployServiceStorageTest.java, runtime/src/main/resources/application-mysql.properties, runtime/src/main/resources/application.properties, runtime/src/test/java/org/eclipse/xpanse/runtime/modules/common/OpenApiGeneratorJarManageTest.java
fixes https://github.com/eclipse-xpanse/xpanse/issues/1031
Before adding an enumeration value：
H2 DB:
MySQL DB:
After adding enumeration values and restarting：
H2 DB:
MySQL DB:
=> Automatically update data table field enumeration values based on code

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/async/TaskConfiguration.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeployment.java, modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/TerraformDeploymentTest.java, modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/utils/ServiceTemplateOpenApiGenerator.java, modules/workflow/src/main/java/org/eclipse/xpanse/modules/workflow/utils/WorkflowProcessUtils.java
=> update async task executor bean to unique name

samples/develop/huawei-compute-opentofu-dev.json, samples/develop/huawei-compute-opentofu-dev.yml, samples/develop/huawei-compute-terraform-dev.json, samples/develop/huawei-compute-terraform-dev.yml, samples/flexibleEngine-K8S.yml, samples/flexibleEngine-Kafka.yml, samples/huawei-Kafka-terraform_module.yml, samples/huawei-Kafka.yml, samples/openstack-Kafka.yml, samples/scs-Kafka.yml
fixes #1342 
Contains all supported resource types:
Both of deployers `OpenTofu` and `Teraform`  are supporeed:
Deployment failed test:(chose flavor 'flavor-error-test')
=> Update and add service templates for development

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceCatalogApi.java, modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/handler/RegistrationExceptionHandler.java, modules/api/src/test/java/org/eclipse/xpanse/api/exceptions/handler/RegistrationExceptionHandlerTest.java, modules/database/src/test/java/org/eclipse/xpanse/modules/database/servicetemplate/ServiceTemplateEntityTest.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/response/ResultType.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/enums/ServiceRegistrationState.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/exceptions/ServiceTemplateNotApproved.java, modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/enums/ServiceRegistrationStateTest.java, modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/exceptions/ServiceTemplateNotApprovedTest.java, modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/view/ServiceTemplateDetailVoTest.java, modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java, modules/servicetemplate/src/test/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManageTest.java, runtime/src/test/java/org/eclipse/xpanse/runtime/CspServiceTemplateApiTest.java, runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceCatalogApiTest.java, runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java, runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceTemplateApiTest.java, runtime/src/test/java/org/eclipse/xpanse/runtime/database/mysql/DeploymentWithMysqlTest.java, runtime/src/test/java/org/eclipse/xpanse/runtime/modules/servicetemplate/utils/ServiceTemplateOpenApiGeneratorTest.java, samples/develop/huawei-compute-opentofu-dev.json, samples/develop/huawei-compute-terraform-dev.json
fixes #1382 
ISV user view details of registered service template:
End user view details of registered service template:
End user deploy service when found service template not approved:
=> introduce approval status to service registration

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/CspServiceTemplateApi.java, modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceCatalogApi.java, modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceTemplateApi.java, modules/security/src/main/java/org/eclipse/xpanse/modules/security/IdentityProviderManager.java, modules/security/src/main/java/org/eclipse/xpanse/modules/security/common/CurrentUserInfo.java, modules/security/src/main/java/org/eclipse/xpanse/modules/security/zitadel/ZitadelIdentityProviderService.java, modules/security/src/main/java/org/eclipse/xpanse/modules/security/zitadel/config/ZitadelOauth2Constant.java, modules/security/src/test/java/org/eclipse/xpanse/modules/security/IdentityProviderManagerTest.java, modules/security/src/test/java/org/eclipse/xpanse/modules/security/common/CurrentUserInfoHolderTest.java, modules/security/src/test/java/org/eclipse/xpanse/modules/security/common/CurrentUserInfoTest.java, modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java, modules/servicetemplate/src/test/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManageTest.java, runtime/src/test/java/org/eclipse/xpanse/runtime/CspServiceTemplateApiTest.java, runtime/src/test/resources/jwt_admin_csp.json, runtime/src/test/resources/jwt_all_roles.json
fixes https://github.com/eclipse-xpanse/xpanse/issues/1405
related to https://github.com/eclipse-xpanse/xpanse-iam/pull/19
Isv user registered service template with with csp `flexibleEngine`:
Csp user with the value `huawei` of the key `csp` in metadata list service templates only return service templates with csp `huawei`:
Csp user with the value `huawei` of the key `csp` in metadata get details of service templates with csp `flexibleEngine`:
Csp user with the value `huawei` of the key `csp` in metadata review service template with csp `flexibleEngine`:
=> Filter Csp user managed service templates with csp value in metadata

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/AuthorizationApi.java, modules/security/src/main/java/org/eclipse/xpanse/modules/security/noauth/OpenApiNoAuthConfig.java, runtime/src/main/resources/application-noauth.properties
fixes #1498 
When  the application  is running with the profile `noauth`,  all the APIs can be called successfully without authentication.
=> make authentication in API layer optional

modules/api/src/test/resources/ocl_terraform_test.yml, modules/deployment/src/test/resources/ocl_terraform_from_git_test.yml, modules/deployment/src/test/resources/ocl_terraform_test.yml, modules/models/src/test/resources/ocl_terraform_test.yml, modules/security/src/main/java/org/eclipse/xpanse/modules/security/IdentityProviderManager.java, modules/security/src/main/java/org/eclipse/xpanse/modules/security/Oauth2WebSecurityFilter.java, modules/security/src/main/java/org/eclipse/xpanse/modules/security/OpenApiOauth2Config.java, modules/security/src/main/java/org/eclipse/xpanse/modules/security/RequiredRoleDescriptionCustomizer.java, modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/utils/ServiceTemplateOpenApiGenerator.java, runtime/src/main/resources/application-noauth.properties, runtime/src/main/resources/application-oauth.properties, runtime/src/test/java/org/eclipse/xpanse/runtime/modules/servicetemplate/utils/ServiceTemplateOpenApiGeneratorTest.java, samples/develop/huawei-compute-opentofu-dev.yml, samples/develop/huawei-compute-terraform-dev.yml, samples/develop/openstack-compute-terraform-dev.yml
fixes #1493
When the configuration property `enable.role.protection` is true:
Authorize with the user 'csp-huawei' only has role 'csp':
Request the API required role admin or isv or user, and the service returns 403.
When the configuration property `enable.role.protection` is false:
Authorize with the user 'csp-huawei' only has role 'csp':
Request the same API and the service returns 200.
=> make all role protection in the API layer optional

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceDeployerApi.java, modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceMigrationApi.java, modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/handler/DeploymentExceptionHandler.java, modules/api/src/test/java/org/eclipse/xpanse/api/exceptions/handler/DeploymentExceptionHandlerTest.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/response/ResultType.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/deploy/exceptions/ServiceLockedException.java, runtime/src/test/java/org/eclipse/xpanse/runtime/ExistingCloudResourcesApiTest.java, runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java, runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceMigrationApiTest.java
fixes #1534 
When deployed service with lock config `{"destroyLocked":true,"modifyLocked":true}`
Destroy the service failed:
Modify the service failed:
Migrate the service failed:
=> Secure services based on lock config

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java
fixes #1562 
Service state before modification:
Service state after modification failure:
fixes  #1565 
Service state before deletion:
Service state after deletion failure:
Service state after deletion success:
=> Update service status based on different task results

plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/common/FlexibleEngineClient.java, plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/common/HuaweiCloudClient.java, runtime/src/main/resources/application.properties, runtime/src/main/resources/logback.xml
fixes https://github.com/eclipse-xpanse/xpanse/issues/1673
By default, the Huawei Cloud SDK only outputs access logs:
When configuring `huaweicloud.sdk.debug.http.listener.enabled=true`, the Huawei Cloud SDK will also output debug logs:
=> add debug logging to HuaweiCloud SDK conditionally

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceDeployerApi.java, modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceStateManageApi.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployServiceEntityToDeployTaskConverter.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceStateManager.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/callbacks/OpenTofuDeploymentResultCallbackManager.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/callbacks/TerraformDeploymentResultCallbackManager.java, runtime/src/test/java/org/eclipse/xpanse/runtime/IsvServiceDeployerApiTest.java, runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java, runtime/src/test/java/org/eclipse/xpanse/runtime/database/mysql/DeploymentWithMysqlTest.java, runtime/src/test/java/org/eclipse/xpanse/runtime/util/ApisTestCommon.java
fixes #1687 
New API to redeploy service with id:
Redeploy the service not with failed state return 400:
Redeploy the service with failed state return 202:
=> Add API to redeploy services with failed state

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceDeployerApi.java, modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServicePricingApi.java, runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java, runtime/src/test/java/org/eclipse/xpanse/runtime/ServicePricingApiTest.java
fixes #1760 
Return errors with error credential:
Return correct data with correct credential not cached errors:
=> Delete controller cache to prevent return errors

modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceorder/ServiceOrderEntity.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/opentofulocal/OpenTofuLocalDeployment.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/opentofulocal/OpenTofuLocalExecutor.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformlocal/TerraformLocalDeployment.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformlocal/TerraformLocalExecutor.java
Fixed https://github.com/eclipse-xpanse/xpanse/issues/1831
Related to https://github.com/eclipse-xpanse/tofu-maker/pull/44 and https://github.com/eclipse-xpanse/terraform-boot/pull/123
=> Clean up files have been read in workspace

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceStateManager.java, runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceStateManageApiTest.java, samples/compute/FlexibleEngine-Compute-terraform-dev.yml, samples/compute/HuaweiCloud-Compute-opentofu-dev.yml, samples/compute/HuaweiCloud-Compute-terraform-dev-autofill.yml, samples/compute/HuaweiCloud-Compute-terraform-dev-git-repo.yml, samples/compute/HuaweiCloud-Compute-terraform-dev.yml
Fixed https://github.com/eclipse-xpanse/xpanse/issues/1922
Restart service with state `MODIFICATION SUCCESSFUL` successfully:
Stop service with state `MODIFICATION SUCCESSFUL` successfully:
Start service with state `MODIFICATION SUCCESSFUL` successfully:
=> support manage service state after modification

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceConfigurationApi.java, modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/handler/ServiceConfigurationExceptionHandler.java, modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceconfiguration/ServiceConfigurationEntity.java, modules/database/src/main/java/org/eclipse/xpanse/modules/database/utils/EntityTransUtils.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceConfigurationManager.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/response/ResultType.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/serviceconfiguration/ServiceConfigurationDetails.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/serviceconfiguration/exceptions/ServiceConfigurationNotFoundException.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/serviceconfiguration/exceptions/ServiceConfigurationUpdateRequestNotFoundException.java
=> create API method to get current configuration of the service

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/deployertools/DeployerToolVersionsCache.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/deployertools/DeployerToolVersionsCacheManager.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/deployertools/DeployerToolVersionsFetcher.java
Fixed https://github.com/eclipse-xpanse/xpanse/issues/2089
Related to https://github.com/eclipse-xpanse/tofu-maker/pull/78 and  https://github.com/eclipse-xpanse/terraform-boot/pull/159
Initializing versions cache after the application started:
=> Optimize method for initializing cache of versions of the deployer tool

modules/api/src/test/java/org/eclipse/xpanse/api/config/ServiceTemplateRegistrationStateConverterTest.java, modules/api/src/test/java/org/eclipse/xpanse/api/config/TaskStatusEnumConverterTest.java, modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicetemplate/ServiceTemplateEntity.java, modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicetemplatehistory/DatabaseServiceTemplateHistoryStorage.java, modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicetemplatehistory/ServiceTemplateHistoryEntity.java, modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicetemplatehistory/ServiceTemplateHistoryRepository.java, modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicetemplatehistory/ServiceTemplateHistoryStorage.java, modules/database/src/test/java/org/eclipse/xpanse/modules/database/servicetemplate/ServiceTemplateEntityTest.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/enums/TaskStatus.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/enums/ServiceTemplateChangeStatus.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/enums/ServiceTemplateRequestType.java, modules/models/src/test/java/org/eclipse/xpanse/modules/models/service/enums/TaskStatusTest.java, modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/enums/ServiceTemplateRegistrationStateTest.java, modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java
Fixed https://github.com/eclipse-xpanse/xpanse/issues/2099
Constructor of table service_template_history in H2 database:
Constructor of table service_template_history in MySql database:
=> Add new table SERVICE_TEMPLATE_HISTORY

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceDeployerApi.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java, runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java, runtime/src/test/java/org/eclipse/xpanse/runtime/database/mysql/DeploymentWithMysqlTest.java
**Fixed https://github.com/eclipse-xpanse/xpanse/issues/2105**
New service getOrderdableServiceDetailsByServiceId:
Call service getOrderdableServiceDetailsByServiceId work well:
Call service getOrderdableServiceDetailsByServiceId throw exception:
=> Create new API to query used service template by service id

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/IsvCloudCredentialsApi.java, modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceCatalogApi.java, modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceMigrationApi.java, modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceTemplateApi.java, modules/api/src/main/java/org/eclipse/xpanse/api/controllers/UserCloudCredentialsApi.java, modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/handler/RegistrationExceptionHandler.java, modules/api/src/test/java/org/eclipse/xpanse/api/exceptions/handler/RegistrationExceptionHandlerTest.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/response/ErrorType.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/exceptions/ServiceTemplateDisabledException.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/view/ServiceTemplateDetailVo.java, modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/exceptions/ServiceTemplateDisabledExceptionTest.java, modules/models/src/test/java/org/eclipse/xpanse/modules/models/servicetemplate/view/ServiceTemplateDetailVoTest.java, modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java, runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceCatalogApiTest.java, runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java, runtime/src/test/java/org/eclipse/xpanse/runtime/database/mysql/RegistrationWithMysqlTest.java
**Related to https://github.com/eclipse-xpanse/xpanse-ui/pull/1323**
**Fixed https://github.com/eclipse-xpanse/xpanse/issues/2102**
Call service `getAllServiceTemplatesByIsv` return service templates with ServiceTemplateRegistrationState, isAvailableInCatalog and isUpdatePending state:
**Fixed https://github.com/eclipse-xpanse/xpanse/issues/2103**
Call service `getOrderableServices` return service templates with AVAILABLE_IN_CATALOG=true
**Fixed https://github.com/eclipse-xpanse/xpanse/issues/2104**
Call service `getOrderableServiceDetailsById` throw ServiceTemplateDisabledException
=> Implement changes to service template query Apis

modules/api/src/main/java/org/eclipse/xpanse/api/config/GetCspInfoFromRequest.java, modules/api/src/main/java/org/eclipse/xpanse/api/config/ServiceTemplateChangeStatusEnumConverter.java, modules/api/src/main/java/org/eclipse/xpanse/api/config/ServiceTemplateRequestTypeEnumConverter.java, modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceTemplateApi.java, modules/api/src/main/java/org/eclipse/xpanse/api/exceptions/handler/RegistrationExceptionHandler.java, modules/api/src/test/java/org/eclipse/xpanse/api/config/ServiceTemplateChangeStatusEnumConverterTest.java, modules/api/src/test/java/org/eclipse/xpanse/api/config/ServiceTemplateRequestTypeEnumConverterTest.java, modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceorder/DatabaseServiceOrderStorage.java, modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicetemplatehistory/DatabaseServiceTemplateHistoryStorage.java, modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicetemplatehistory/ServiceTemplateHistoryEntity.java, modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicetemplatehistory/ServiceTemplateHistoryStorage.java, modules/database/src/main/java/org/eclipse/xpanse/modules/database/utils/EntityTransUtils.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/response/ErrorType.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/change/ServiceTemplateChangeInfo.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/change/ServiceTemplateHistoryVo.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/change/enums/ServiceTemplateChangeStatus.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/change/enums/ServiceTemplateRequestType.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/change/exceptions/ServiceTemplateChangeRequestNotFound.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/exceptions/ServiceTemplateNotRegistered.java, modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java, runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceTemplateApiTest.java, runtime/src/test/java/org/eclipse/xpanse/runtime/database/mysql/DeploymentWithMysqlTest.java, runtime/src/test/java/org/eclipse/xpanse/runtime/database/mysql/RegistrationWithMysqlTest.java, runtime/src/test/java/org/eclipse/xpanse/runtime/util/ApisTestCommon.java
**Fixed https://github.com/eclipse-xpanse/xpanse/issues/2106**
**New service `getServiceTemplateHistoryById`:**
Call this service with serviceTemplateId well:
Call this service throw exception:
**New service `getRequestedServiceTemplateByChangeId`:**
Call this service with changeId well:
Call this service throw exception:
=> Query service template history and query request ocl by changeId

modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java
Fixed https://github.com/eclipse-xpanse/xpanse/issues/2187
Register a service template with namespace 'ISV-A' successfully:
Update the service template with changed namespace 'ISV-B' thrown exception:
=> namespace validation in service template update requests

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/opentofulocal/OpenTofuLocalDeployment.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformlocal/TerraformLocalDeployment.java
**Fixed https://github.com/eclipse-xpanse/xpanse/issues/2150**
Deploy service without credentials:
After deploy failed, there is no rollback order to destroy resources any more:
Add credentials successfully:
Retry to deploy the failed service and then  the retry is successful:
=> Fix error when deployment fails with missing credentials

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceTemplateApi.java, modules/api/src/test/java/org/eclipse/xpanse/api/config/ServiceTemplateRegistrationStateConverterTest.java, modules/api/src/test/java/org/eclipse/xpanse/api/config/ServiceTemplateRequestStatusEnumConverterTest.java, modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicetemplaterequest/DatabaseServiceTemplateRequestHistoryStorage.java, modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicetemplaterequest/ServiceTemplateRequestHistoryStorage.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/enums/ServiceTemplateRegistrationState.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/request/enums/ServiceTemplateRequestStatus.java, modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java, runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceTemplateApiTest.java
Fixed https://github.com/eclipse-xpanse/xpanse/issues/2199
Add new API to cancel service template request:
Register service template , approve the register request, update the service template: 
Cancel update request in status 'IN-REVIEW' well:
Cancel request not in status 'IN-REVIEW' returns error:
=> Add service to cancel service template request

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceTemplateApi.java, modules/api/src/test/java/org/eclipse/xpanse/api/config/ServiceTemplateRequestTypeEnumConverterTest.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/request/enums/ServiceTemplateRequestType.java, modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java, runtime/src/test/java/org/eclipse/xpanse/runtime/CspServiceTemplateApiTest.java, runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceTemplateApiTest.java, runtime/src/test/java/org/eclipse/xpanse/runtime/database/mysql/RegistrationWithMysqlTest.java
**Fixed https://github.com/eclipse-xpanse/xpanse/issues/2232
Related to https://github.com/eclipse-xpanse/xpanse-ui/pull/1377**
Register service template with `auto-approve` is false:
In this state, `isAvailableInCatalog=false` , `registrationState=IN-REVIEW`, `isReviewInProgress=true`, operations `Update` and `Delete` are available:
Approved service template and the update service template with ‘isRemovedUtilApproved’ is true:
In this state,  `isAvailableInCatalog=false` , `registrationState=APPROVED`, `isReviewInProgress=true`, operations `Delete` is available:
Approve the update request, in this case, operations `Update` and `Unpublish` are available:
Unpublish the service template successfully;
In this case, the operations `Update`,`Republish` and `Delete` are available:
Republish the …
=> rename service template methods and enums

modules/api/src/main/java/org/eclipse/xpanse/api/config/GetCspInfoFromRequest.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/enums/ServiceTemplateReviewPluginResultType.java, modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/OrchestratorPlugin.java, modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/servicetemplate/ServiceTemplateManager.java, modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java, plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/FlexibleEngineOrchestratorPlugin.java, plugins/flexibleengine/src/test/java/org/eclipse/xpanse/plugins/flexibleengine/FlexibleEngineOrchestratorPluginTest.java, plugins/huaweicloud/src/main/java/org/eclipse/xpanse/plugins/huaweicloud/HuaweiCloudOrchestratorPlugin.java, plugins/huaweicloud/src/test/java/org/eclipse/xpanse/plugins/huaweicloud/HuaweiCloudOrchestratorPluginTest.java, plugins/openstacktestlab/src/main/java/org/eclipse/xpanse/plugins/openstacktestlab/OpenstackTestlabOrchestratorPlugin.java, plugins/openstacktestlab/src/test/java/org/eclipse/xpanse/plugins/openstacktestlab/OpenstackTestlabOrchestratorPluginTest.java, plugins/plusserver/src/main/java/org/eclipse/xpanse/plugins/plusserver/PlusServerOrchestratorPlugin.java, plugins/plusserver/src/test/java/org/eclipse/xpanse/plugins/plusserver/PlusServerOrchestratorPluginTest.java, plugins/regiocloud/src/main/java/org/eclipse/xpanse/plugins/regiocloud/RegioCloudOrchestratorPlugin.java, plugins/regiocloud/src/test/java/org/eclipse/xpanse/plugins/regiocloud/RegioCloudOrchestratorPluginTest.java
Fixed https://github.com/eclipse-xpanse/xpanse/issues/2226
Register service template with  auto-approved is disabled of `HuaweiCloud`:
Register service template with  auto-approved is enabled of `FlexibleEngine`:
=> add plugin methods to manage the lifecycle of service templates

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java
**Fixed https://github.com/eclipse-xpanse/xpanse/issues/2263**
When deploy service successfully, the state of service is `running`:
When deploy service failed, the state of service is `not running`:
**Fixed https://github.com/eclipse-xpanse/xpanse/issues/2249**
Migrate service successfully:
The state of old service is `not running` and the state of new service  is `running`:
=> update state of service after deployment order completed

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/deployertools/DeployerToolUtils.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/opentofulocal/OpenTofuLocalDeployment.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformlocal/TerraformLocalDeployment.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/DeploymentScriptsHelper.java, plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/resourcehandler/FlexibleEngineTerraformResourceHandler.java
Fixed https://github.com/eclipse-xpanse/xpanse/issues/2254
Related to https://github.com/eclipse-xpanse/xpanse-samples/pull/17
Related to https://github.com/eclipse-xpanse/terraform-boot/pull/181
Related to https://github.com/eclipse-xpanse/tofu-maker/pull/99
Deploy service with `terraformLocal` successfully:
Deploy service with `openTofuLocal` successfully:
=> fix and handle errors when processing deployment result

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceStateManager.java, runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceRecreateApiTest.java, runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceStateManageApiTest.java
**Fixed https://github.com/eclipse-xpanse/xpanse/issues/2274
Related to https://github.com/eclipse-xpanse/xpanse-ui/pull/1405**
When service is not locked:
Lock service:
Recreate/Stop/Restart is disabled:
=> service state management validate lock for modification

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/CspServiceTemplateApi.java, modules/api/src/main/java/org/eclipse/xpanse/api/controllers/IsvCloudCredentialsApi.java, modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialCenter.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceDetailsViewManager.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironments.java, modules/security/src/main/java/org/eclipse/xpanse/modules/security/UserServiceHelper.java, modules/security/src/test/java/org/eclipse/xpanse/modules/security/UserServiceHelperTest.java, modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java, pom.xml, runtime/src/test/java/org/eclipse/xpanse/runtime/IsvCloudCredentialsApiTest.java
Fixed https://github.com/eclipse-xpanse/xpanse/issues/2308
ISV user ISV-A add credential with key which contains managed isv by user:
ISV users manage other isv could not view the created credential anymore:
=> isv credential set managed service vendor as userId

README.md, modules/deployment/pom.xml, modules/policy/pom.xml
Fixed  https://github.com/eclipse-xpanse/xpanse/issues/2407
Susscced on Windows:
Susscced on Linux:
=> Fix Maven Plugin Generate API Client Failed on Windows

modules/database/src/test/java/org/eclipse/xpanse/modules/database/serviceconfiguration/ServiceConfigurationEntityTest.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployServiceEntityConverter.java, modules/deployment/src/test/java/org/eclipse/xpanse/modules/deployment/ServiceDeploymentEntityConverterTest.java
org.eclipse.xpanse.modules.deployment.DeployServiceEntityConverter#getInitialServiceConfiguration
Set updated time at time of creations.
fixes #2396
=> Set updated time for Service Configuration Entity

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironments.java, runtime/src/test/java/org/eclipse/xpanse/runtime/database/mysql/DeploymentWithMysqlTest.java
Fixed https://github.com/eclipse-xpanse/xpanse/issues/2466
Destroy a deployed service with null deployment_input_properties successfully:
=> Fix destroy failed when deployed service with null serviceRequestProperties

modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServicePortingApi.java, modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceRecreateApi.java, modules/database/src/main/java/org/eclipse/xpanse/modules/database/service/ServiceDeploymentEntity.java, modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceorder/ServiceOrderEntity.java, modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicetemplate/ServiceTemplateEntity.java, modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicetemplaterequest/ServiceTemplateRequestHistoryEntity.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceChangeRequestsManager.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceDeploymentEntityConverter.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceOrderManager.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceStateManager.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/recreate/steps/StartRecreateDeploy.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/servicelock/ServiceLockConfigService.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/serviceporting/steps/StartDeploy.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/MdcUtils.java, modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java, modules/workflow/src/main/java/org/eclipse/xpanse/modules/workflow/utils/WorkflowUtils.java, runtime/src/test/java/org/eclipse/xpanse/runtime/ServiceDeployerApiTest.java
Fixed #2428
register:
deployment:
recreate:
port:
=> Feature/generate UUID

modules/database/src/main/java/org/eclipse/xpanse/modules/database/servicechange/DatabaseServiceChangeRequestStorage.java, modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceobject/DatabaseServiceObjectStorage.java, modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceobject/ServiceObjectEntity.java, modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceobject/ServiceObjectRepository.java, modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceobject/ServiceObjectStorage.java, modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceorder/ServiceOrderEntity.java, modules/database/src/test/java/org/eclipse/xpanse/modules/database/serviceobject/DatabaseServiceObjectStorageTest.java, modules/database/src/test/java/org/eclipse/xpanse/modules/database/serviceobject/ServiceObjectEntityTest.java, modules/database/src/test/java/org/eclipse/xpanse/modules/database/serviceorder/ServiceOrderEntityTest.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceActionManager.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceChangeRequestsManager.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceConfigurationManager.java, modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceOrderManager.java, modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/order/enums/ServiceOrderType.java
=> create SERVICE_OBJECTS and SERVICE_DEPENDENT_OBJECT table

modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
Fixed https://github.com/eclipse-xpanse/xpanse/issues/2511
Recreate service successfully:
Destroy service successfully:
=> Fix destroy service failed
